// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/streamvesting/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgTransferWithVesting is the request type for transferring tokens with vesting.
type MsgTransferWithVesting struct {
	// sender is the address of the account sending the tokens.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// recipient is the address of the account receiving the vesting tokens.
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// amount is the coins to transfer with vesting.
	Amount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
	// vesting_epochs is the number of epochs over which the tokens will vest.
	// If not specified or 0, defaults to 180 epochs.
	VestingEpochs uint64 `protobuf:"varint,4,opt,name=vesting_epochs,json=vestingEpochs,proto3" json:"vesting_epochs,omitempty"`
}

func (m *MsgTransferWithVesting) Reset()         { *m = MsgTransferWithVesting{} }
func (m *MsgTransferWithVesting) String() string { return proto.CompactTextString(m) }
func (*MsgTransferWithVesting) ProtoMessage()    {}
func (*MsgTransferWithVesting) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{2}
}
func (m *MsgTransferWithVesting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferWithVesting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferWithVesting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferWithVesting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferWithVesting.Merge(m, src)
}
func (m *MsgTransferWithVesting) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferWithVesting) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferWithVesting.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferWithVesting proto.InternalMessageInfo

func (m *MsgTransferWithVesting) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgTransferWithVesting) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgTransferWithVesting) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *MsgTransferWithVesting) GetVestingEpochs() uint64 {
	if m != nil {
		return m.VestingEpochs
	}
	return 0
}

// MsgTransferWithVestingResponse defines the response for MsgTransferWithVesting.
type MsgTransferWithVestingResponse struct {
}

func (m *MsgTransferWithVestingResponse) Reset()         { *m = MsgTransferWithVestingResponse{} }
func (m *MsgTransferWithVestingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferWithVestingResponse) ProtoMessage()    {}
func (*MsgTransferWithVestingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{3}
}
func (m *MsgTransferWithVestingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferWithVestingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferWithVestingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferWithVestingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferWithVestingResponse.Merge(m, src)
}
func (m *MsgTransferWithVestingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferWithVestingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferWithVestingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferWithVestingResponse proto.InternalMessageInfo

// BatchVestingOutput defines one recipient output in batch transfer with vesting.
type BatchVestingOutput struct {
	// recipient is the address of the account receiving vesting tokens.
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// amount is the coins to transfer with vesting.
	Amount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *BatchVestingOutput) Reset()         { *m = BatchVestingOutput{} }
func (m *BatchVestingOutput) String() string { return proto.CompactTextString(m) }
func (*BatchVestingOutput) ProtoMessage()    {}
func (*BatchVestingOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{4}
}
func (m *BatchVestingOutput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchVestingOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchVestingOutput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchVestingOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchVestingOutput.Merge(m, src)
}
func (m *BatchVestingOutput) XXX_Size() int {
	return m.Size()
}
func (m *BatchVestingOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchVestingOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BatchVestingOutput proto.InternalMessageInfo

func (m *BatchVestingOutput) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *BatchVestingOutput) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

// MsgBatchTransferWithVesting is the request type for batch transfer with vesting.
type MsgBatchTransferWithVesting struct {
	// sender is the address of the account sending the tokens.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// outputs are recipients and amounts to vest.
	Outputs []BatchVestingOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs"`
	// vesting_epochs is the number of epochs over which the tokens will vest.
	// If not specified or 0, defaults to 180 epochs.
	VestingEpochs uint64 `protobuf:"varint,3,opt,name=vesting_epochs,json=vestingEpochs,proto3" json:"vesting_epochs,omitempty"`
}

func (m *MsgBatchTransferWithVesting) Reset()         { *m = MsgBatchTransferWithVesting{} }
func (m *MsgBatchTransferWithVesting) String() string { return proto.CompactTextString(m) }
func (*MsgBatchTransferWithVesting) ProtoMessage()    {}
func (*MsgBatchTransferWithVesting) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{5}
}
func (m *MsgBatchTransferWithVesting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBatchTransferWithVesting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBatchTransferWithVesting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBatchTransferWithVesting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBatchTransferWithVesting.Merge(m, src)
}
func (m *MsgBatchTransferWithVesting) XXX_Size() int {
	return m.Size()
}
func (m *MsgBatchTransferWithVesting) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBatchTransferWithVesting.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBatchTransferWithVesting proto.InternalMessageInfo

func (m *MsgBatchTransferWithVesting) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgBatchTransferWithVesting) GetOutputs() []BatchVestingOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *MsgBatchTransferWithVesting) GetVestingEpochs() uint64 {
	if m != nil {
		return m.VestingEpochs
	}
	return 0
}

// MsgBatchTransferWithVestingResponse defines the response for MsgBatchTransferWithVesting.
type MsgBatchTransferWithVestingResponse struct {
}

func (m *MsgBatchTransferWithVestingResponse) Reset()         { *m = MsgBatchTransferWithVestingResponse{} }
func (m *MsgBatchTransferWithVestingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBatchTransferWithVestingResponse) ProtoMessage()    {}
func (*MsgBatchTransferWithVestingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50f3863e46541da3, []int{6}
}
func (m *MsgBatchTransferWithVestingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBatchTransferWithVestingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBatchTransferWithVestingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBatchTransferWithVestingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBatchTransferWithVestingResponse.Merge(m, src)
}
func (m *MsgBatchTransferWithVestingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBatchTransferWithVestingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBatchTransferWithVestingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBatchTransferWithVestingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "inference.streamvesting.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "inference.streamvesting.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgTransferWithVesting)(nil), "inference.streamvesting.MsgTransferWithVesting")
	proto.RegisterType((*MsgTransferWithVestingResponse)(nil), "inference.streamvesting.MsgTransferWithVestingResponse")
	proto.RegisterType((*BatchVestingOutput)(nil), "inference.streamvesting.BatchVestingOutput")
	proto.RegisterType((*MsgBatchTransferWithVesting)(nil), "inference.streamvesting.MsgBatchTransferWithVesting")
	proto.RegisterType((*MsgBatchTransferWithVestingResponse)(nil), "inference.streamvesting.MsgBatchTransferWithVestingResponse")
}

func init() { proto.RegisterFile("inference/streamvesting/tx.proto", fileDescriptor_50f3863e46541da3) }

var fileDescriptor_50f3863e46541da3 = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6b, 0xd4, 0x40,
	0x18, 0xde, 0xd9, 0xad, 0x2b, 0x9d, 0xfa, 0x81, 0xb1, 0xd8, 0x34, 0x42, 0x1a, 0xa2, 0x85, 0x58,
	0x69, 0xd2, 0x56, 0xab, 0x58, 0x7a, 0xd0, 0x48, 0x4f, 0xb2, 0x28, 0x5b, 0x3f, 0xc0, 0x4b, 0xc9,
	0x26, 0xd3, 0xec, 0x28, 0x99, 0x09, 0x33, 0x93, 0xd2, 0x9e, 0x14, 0x8f, 0x3d, 0x88, 0x3f, 0x43,
	0x3c, 0xf5, 0x20, 0xfe, 0x86, 0x82, 0x97, 0x22, 0x08, 0x9e, 0x54, 0xda, 0x43, 0xff, 0x86, 0x24,
	0x99, 0xdd, 0xba, 0x6b, 0x12, 0xb5, 0xe8, 0x65, 0xb3, 0x79, 0x3f, 0x9e, 0x79, 0x9f, 0xe7, 0x79,
	0x67, 0x17, 0x1a, 0x98, 0xac, 0x23, 0x86, 0x88, 0x8f, 0x1c, 0x2e, 0x18, 0xf2, 0xa2, 0x0d, 0xc4,
	0x05, 0x26, 0xa1, 0x23, 0x36, 0xed, 0x98, 0x51, 0x41, 0x95, 0x89, 0x7e, 0x85, 0x3d, 0x50, 0xa1,
	0x9d, 0xf3, 0x22, 0x4c, 0xa8, 0x93, 0x7d, 0xe6, 0xb5, 0xda, 0x84, 0x4f, 0x79, 0x44, 0xb9, 0x13,
	0xf1, 0xd0, 0xd9, 0x98, 0x4f, 0x1f, 0x32, 0x31, 0x99, 0x27, 0xd6, 0xb2, 0x37, 0x27, 0x7f, 0x91,
	0xa9, 0xf1, 0x90, 0x86, 0x34, 0x8f, 0xa7, 0xdf, 0x64, 0x54, 0x97, 0x48, 0x1d, 0x8f, 0x23, 0x67,
	0x63, 0xbe, 0x83, 0x84, 0x37, 0xef, 0xf8, 0x14, 0x13, 0x99, 0xbf, 0x5c, 0x36, 0x77, 0xec, 0x31,
	0x2f, 0x92, 0xd8, 0xe6, 0x47, 0x00, 0xcf, 0xb6, 0x78, 0xf8, 0x28, 0x0e, 0x3c, 0x81, 0x1e, 0x64,
	0x19, 0xe5, 0x06, 0x1c, 0xf5, 0x12, 0xd1, 0xa5, 0x0c, 0x8b, 0x2d, 0x15, 0x18, 0xc0, 0x1a, 0x75,
	0xd5, 0x4f, 0xef, 0x67, 0xc7, 0xe5, 0x50, 0x77, 0x82, 0x80, 0x21, 0xce, 0x57, 0x05, 0xc3, 0x24,
	0x6c, 0x1f, 0x95, 0x2a, 0x2e, 0x6c, 0xe6, 0xd8, 0x6a, 0xdd, 0x00, 0xd6, 0xd8, 0xc2, 0x94, 0x5d,
	0x22, 0x8c, 0x9d, 0x1f, 0xe4, 0x8e, 0xee, 0x7e, 0x9d, 0xaa, 0xbd, 0x3d, 0xdc, 0x99, 0x01, 0x6d,
	0xd9, 0xb9, 0xb4, 0xfc, 0xea, 0x70, 0x67, 0xe6, 0x08, 0x73, 0xfb, 0x70, 0x67, 0xe6, 0xca, 0x11,
	0x91, 0xcd, 0x21, 0x2a, 0x43, 0x93, 0x9b, 0x93, 0x70, 0x62, 0x28, 0xd4, 0x46, 0x3c, 0xa6, 0x84,
	0x23, 0xf3, 0x73, 0x1d, 0x5e, 0x68, 0xf1, 0xf0, 0x21, 0xf3, 0x08, 0x5f, 0x47, 0xec, 0x09, 0x16,
	0xdd, 0xc7, 0x39, 0x8a, 0x32, 0x07, 0x9b, 0x1c, 0x91, 0x00, 0xb1, 0xdf, 0x92, 0x95, 0x75, 0xa9,
	0x42, 0x0c, 0xf9, 0x38, 0xc6, 0x88, 0x88, 0x8c, 0x6c, 0xa5, 0x42, 0xfd, 0x52, 0xa5, 0x0b, 0x9b,
	0x5e, 0x44, 0x13, 0x22, 0xd4, 0x86, 0xd1, 0xb0, 0xc6, 0x16, 0x26, 0x6d, 0xd9, 0x91, 0x9a, 0x68,
	0x4b, 0x13, 0xed, 0xbb, 0x14, 0x13, 0x77, 0x31, 0xd5, 0xe6, 0xdd, 0xb7, 0x29, 0x2b, 0xc4, 0xa2,
	0x9b, 0x74, 0x6c, 0x9f, 0x46, 0x72, 0x2b, 0xe4, 0x63, 0x96, 0x07, 0xcf, 0x1d, 0xb1, 0x15, 0x23,
	0x9e, 0x35, 0x70, 0xa9, 0x63, 0x8e, 0xaf, 0x4c, 0xc3, 0x33, 0x52, 0xa4, 0x35, 0x14, 0x53, 0xbf,
	0xcb, 0xd5, 0x11, 0x03, 0x58, 0x23, 0xed, 0xd3, 0x32, 0xba, 0x92, 0x05, 0x97, 0x6e, 0xa7, 0x72,
	0x4b, 0x56, 0xa9, 0xd6, 0x73, 0x95, 0x5a, 0x17, 0x88, 0x67, 0x1a, 0x50, 0x2f, 0xce, 0xf4, 0x95,
	0xff, 0x00, 0xa0, 0xe2, 0x7a, 0xc2, 0xef, 0x25, 0xee, 0x27, 0x22, 0x4e, 0xc4, 0xa0, 0x86, 0xe0,
	0x38, 0x1a, 0xd6, 0xff, 0xaf, 0x86, 0xe6, 0x76, 0x1d, 0x5e, 0x6c, 0xf1, 0x30, 0x9b, 0xfd, 0xdf,
	0xec, 0xcd, 0x3d, 0x78, 0x92, 0x66, 0xec, 0xb9, 0x1c, 0xfe, 0x6a, 0xe9, 0x15, 0xf9, 0x55, 0x31,
	0x77, 0x24, 0xa5, 0xd3, 0xee, 0x21, 0x14, 0x58, 0xdc, 0x28, 0xb2, 0x78, 0x65, 0xc8, 0xe2, 0xc5,
	0x4a, 0x8b, 0xcb, 0xc8, 0x9a, 0xd3, 0xf0, 0x52, 0x45, 0xba, 0x67, 0xf6, 0xc2, 0x76, 0x03, 0x36,
	0x5a, 0x3c, 0x54, 0x9e, 0xc1, 0x53, 0x03, 0xbf, 0x29, 0x56, 0x29, 0xd1, 0xa1, 0x0b, 0xab, 0xcd,
	0xfd, 0x69, 0x65, 0xef, 0x4c, 0xe5, 0x05, 0x3c, 0x5f, 0x64, 0x8f, 0x53, 0x05, 0x54, 0xd0, 0xa0,
	0xdd, 0xfc, 0xcb, 0x86, 0xfe, 0x00, 0xaf, 0x01, 0x54, 0x4b, 0xb7, 0xe4, 0x7a, 0x15, 0x6a, 0x59,
	0x97, 0xb6, 0x7c, 0x9c, 0xae, 0xde, 0x40, 0xda, 0x89, 0x97, 0xe9, 0x22, 0xbb, 0xab, 0xbb, 0xfb,
	0x3a, 0xd8, 0xdb, 0xd7, 0xc1, 0xf7, 0x7d, 0x1d, 0xbc, 0x39, 0xd0, 0x6b, 0x7b, 0x07, 0x7a, 0xed,
	0xcb, 0x81, 0x5e, 0x7b, 0x7a, 0xeb, 0xa7, 0x1b, 0x11, 0x33, 0x1a, 0x24, 0xbe, 0xe0, 0x3e, 0xce,
	0x96, 0xa2, 0x7c, 0x3d, 0xb2, 0x8b, 0xd2, 0x69, 0x66, 0x7f, 0x1c, 0xd7, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0xc0, 0x3f, 0x3c, 0x18, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// TransferWithVesting transfers tokens from sender to recipient with a vesting schedule.
	// The tokens will vest over the specified number of epochs (default: 180).
	TransferWithVesting(ctx context.Context, in *MsgTransferWithVesting, opts ...grpc.CallOption) (*MsgTransferWithVestingResponse, error)
	// BatchTransferWithVesting transfers tokens from sender to multiple recipients with vesting schedules.
	BatchTransferWithVesting(ctx context.Context, in *MsgBatchTransferWithVesting, opts ...grpc.CallOption) (*MsgBatchTransferWithVestingResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/inference.streamvesting.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferWithVesting(ctx context.Context, in *MsgTransferWithVesting, opts ...grpc.CallOption) (*MsgTransferWithVestingResponse, error) {
	out := new(MsgTransferWithVestingResponse)
	err := c.cc.Invoke(ctx, "/inference.streamvesting.Msg/TransferWithVesting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BatchTransferWithVesting(ctx context.Context, in *MsgBatchTransferWithVesting, opts ...grpc.CallOption) (*MsgBatchTransferWithVestingResponse, error) {
	out := new(MsgBatchTransferWithVestingResponse)
	err := c.cc.Invoke(ctx, "/inference.streamvesting.Msg/BatchTransferWithVesting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// TransferWithVesting transfers tokens from sender to recipient with a vesting schedule.
	// The tokens will vest over the specified number of epochs (default: 180).
	TransferWithVesting(context.Context, *MsgTransferWithVesting) (*MsgTransferWithVestingResponse, error)
	// BatchTransferWithVesting transfers tokens from sender to multiple recipients with vesting schedules.
	BatchTransferWithVesting(context.Context, *MsgBatchTransferWithVesting) (*MsgBatchTransferWithVestingResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) TransferWithVesting(ctx context.Context, req *MsgTransferWithVesting) (*MsgTransferWithVestingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferWithVesting not implemented")
}
func (*UnimplementedMsgServer) BatchTransferWithVesting(ctx context.Context, req *MsgBatchTransferWithVesting) (*MsgBatchTransferWithVestingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchTransferWithVesting not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inference.streamvesting.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferWithVesting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferWithVesting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferWithVesting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inference.streamvesting.Msg/TransferWithVesting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferWithVesting(ctx, req.(*MsgTransferWithVesting))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BatchTransferWithVesting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBatchTransferWithVesting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BatchTransferWithVesting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inference.streamvesting.Msg/BatchTransferWithVesting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BatchTransferWithVesting(ctx, req.(*MsgBatchTransferWithVesting))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inference.streamvesting.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "TransferWithVesting",
			Handler:    _Msg_TransferWithVesting_Handler,
		},
		{
			MethodName: "BatchTransferWithVesting",
			Handler:    _Msg_BatchTransferWithVesting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference/streamvesting/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferWithVesting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferWithVesting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferWithVesting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VestingEpochs != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VestingEpochs))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferWithVestingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferWithVestingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferWithVestingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *BatchVestingOutput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchVestingOutput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchVestingOutput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBatchTransferWithVesting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBatchTransferWithVesting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBatchTransferWithVesting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VestingEpochs != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VestingEpochs))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBatchTransferWithVestingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBatchTransferWithVestingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBatchTransferWithVestingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferWithVesting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.VestingEpochs != 0 {
		n += 1 + sovTx(uint64(m.VestingEpochs))
	}
	return n
}

func (m *MsgTransferWithVestingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *BatchVestingOutput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgBatchTransferWithVesting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.VestingEpochs != 0 {
		n += 1 + sovTx(uint64(m.VestingEpochs))
	}
	return n
}

func (m *MsgBatchTransferWithVestingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferWithVesting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferWithVesting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferWithVesting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingEpochs", wireType)
			}
			m.VestingEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferWithVestingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferWithVestingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferWithVestingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchVestingOutput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchVestingOutput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchVestingOutput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBatchTransferWithVesting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBatchTransferWithVesting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBatchTransferWithVesting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, BatchVestingOutput{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingEpochs", wireType)
			}
			m.VestingEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBatchTransferWithVestingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBatchTransferWithVestingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBatchTransferWithVestingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
