package types

import "errors"

var (
	ErrInvalidNonce          = errors.New("invalid nonce: must be sequential")
	ErrInvalidUserSig        = errors.New("invalid user signature")
	ErrInvalidProposerSig    = errors.New("invalid proposer signature: not a group member")
	ErrInvalidExecutorSig    = errors.New("invalid executor signature")
	ErrInsufficientBalance   = errors.New("insufficient escrow balance")
	ErrMultipleStartMsgs     = errors.New("at most one MsgStartInference per diff")
	ErrSessionFinalizing     = errors.New("session is finalizing: no new inferences")
	ErrInferenceNotFound     = errors.New("inference not found")
	ErrInferenceSealed       = errors.New("inference sealed: late validation not accepted")
	ErrInvalidTransition     = errors.New("invalid status transition")
	ErrSelfValidation        = errors.New("validator cannot be the executor")
	ErrWrongExecutorSlot     = errors.New("executor_slot does not match assigned executor")
	ErrActualCostExceedsMax  = errors.New("actual cost exceeds reserved cost")
	ErrInsufficientVotes     = errors.New("insufficient votes for timeout")
	ErrInvalidTimeoutReason  = errors.New("timeout reason does not match inference status")
	ErrDuplicateVote         = errors.New("duplicate vote from slot")
	ErrAlreadyFinalizing     = errors.New("session is already finalizing")
	ErrEmptyTx               = errors.New("devshard tx has no message set")
	ErrDuplicateInferenceID  = errors.New("duplicate inference ID")
	ErrInvalidVoteSig        = errors.New("invalid vote signature")
	ErrInvalidInferenceID    = errors.New("inference_id must equal diff nonce")
	ErrCostOverflow          = errors.New("cost calculation overflows uint64")
	ErrSlotNotInGroup        = errors.New("slot not in group")
	ErrHostNotInGroup        = errors.New("host signer address not in group")
	ErrGroupSizeMismatch     = errors.New("hosts count does not match group size")
	ErrPromptHashMismatch    = errors.New("prompt does not match hash in StartInference")
	ErrPayloadMismatch       = errors.New("request payload does not match StartInference params")
	ErrStateHashMismatch     = errors.New("host state hash does not match local state")
	ErrPostStateRootMismatch = errors.New("post_state_root does not match computed state root")
	ErrDuplicateSeedReveal   = errors.New("duplicate seed reveal from same address")
	ErrSeedTooShort          = errors.New("seed signature too short (need >= 8 bytes)")
	ErrSessionNotFinalizing  = errors.New("session is not finalizing")
	ErrInvalidSeedSig        = errors.New("seed signature does not recover to slot owner")
	ErrDuplicateValidation   = errors.New("duplicate validation: address already validated this inference")
	ErrInvalidStateSig       = errors.New("invalid state signature from host")
	ErrSessionSettlement     = errors.New("session is in settlement: seeds are final")
	ErrInvalidGroup          = errors.New("invalid group")
	ErrEscrowIDMismatch      = errors.New("escrow_id does not match session")
	ErrNonceLimitExceeded    = errors.New("nonce exceeds chain max_nonce limit")
)
