FROM golang:1.25.9-alpine3.23 AS builder
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /mockoracle ./e2e/mockoracle

FROM alpine:3.21
COPY --from=builder /mockoracle /usr/bin/mockoracle
CMD ["mockoracle"]
