package keeper

import (
	"context"
	"fmt"
	"strings"

	"cosmossdk.io/collections"
	sdk "github.com/cosmos/cosmos-sdk/types"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
)

// validateIBCTokenForTradeInternal validates an IBC token for trading through liquidity pools
// It performs two validations:
// 1. Verifies that the IBC token has registered metadata in the bank module
// 2. Verifies that the IBC token is registered in the list of approved for trade
func (k Keeper) validateIBCTokenForTradeInternal(ctx context.Context, ibcDenom string) (bool, banktypes.Metadata, error) {
	sdkCtx := sdk.UnwrapSDKContext(ctx)

	// Step 1: Verify that the IBC token is approved for trading AND get its ChainID
	// We need the ChainID to query the custom metadata store if x/bank fails.
	// Since the map is keyed by (ChainId, ContractAddress) and we only have ContractAddress (ibcDenom),
	// we must iterate to find the match and extract the ChainID.

	normalizedDenom := strings.ToLower(ibcDenom)
	var chainId string
	isApproved := false

	iter, err := k.LiquidityPoolApprovedTokensMap.Iterate(sdkCtx, nil)
	if err != nil {
		return false, banktypes.Metadata{}, fmt.Errorf("failed to iterate approved tokens: %w", err)
	}
	defer iter.Close()

	for ; iter.Valid(); iter.Next() {
		key, err := iter.Key()
		if err != nil {
			continue
		}
		// Key is Pair[string, string] -> (ChainId, ContractAddress)
		if key.K2() == normalizedDenom {
			chainId = key.K1()
			isApproved = true
			break
		}
	}

	if !isApproved {
		return false, banktypes.Metadata{}, fmt.Errorf("IBC token %s is not approved for trading", ibcDenom)
	}

	// Step 2: Try governance-registered metadata FIRST (x/inference custom store)
	// This is authoritative - set via MsgRegisterIbcTokenMetadata and always has correct decimals.
	// x/bank IBC metadata is auto-generated by the transfer module and typically lacks decimals.
	if chainId != "" {
		customMetadata, err := k.WrappedTokenMetadataMap.Get(sdkCtx, collections.Join(chainId, normalizedDenom))
		if err == nil {
			return true, banktypes.Metadata{
				Description: fmt.Sprintf("Imported via Governance from %s", chainId),
				DenomUnits: []*banktypes.DenomUnit{
					{
						Denom:    ibcDenom,
						Exponent: 0,
					},
					{
						Denom:    customMetadata.Symbol,
						Exponent: customMetadata.Decimals,
					},
				},
				Base:    ibcDenom,
				Display: customMetadata.Symbol,
				Name:    customMetadata.Name,
				Symbol:  customMetadata.Symbol,
			}, nil
		}
	}

	// Step 3: Fallback - Try x/bank module metadata
	// Only reached if no governance-registered metadata exists for this token
	bankMetadata, found := k.BankView.GetDenomMetaData(sdkCtx, ibcDenom)
	if found {
		// STRICT VALIDATION: Ensure metadata is not "lazy" (missing display unit with exponent > 0)
		if strings.TrimSpace(bankMetadata.Display) != "" {
			for _, unit := range bankMetadata.DenomUnits {
				if unit.Denom == bankMetadata.Display && unit.Exponent > 0 {
					return true, bankMetadata, nil
				}
			}
		}
	}

	return false, banktypes.Metadata{}, fmt.Errorf("valid token metadata not found for approved IBC denom %s (checked x/inference and x/bank)", ibcDenom)
}
