// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package inference

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_PoCChallenge                 protoreflect.MessageDescriptor
	fd_PoCChallenge_epoch_index     protoreflect.FieldDescriptor
	fd_PoCChallenge_challenger      protoreflect.FieldDescriptor
	fd_PoCChallenge_target          protoreflect.FieldDescriptor
	fd_PoCChallenge_expected_reward protoreflect.FieldDescriptor
	fd_PoCChallenge_locked_payment  protoreflect.FieldDescriptor
	fd_PoCChallenge_start_height    protoreflect.FieldDescriptor
	fd_PoCChallenge_seed            protoreflect.FieldDescriptor
	fd_PoCChallenge_state           protoreflect.FieldDescriptor
)

func init() {
	file_inference_inference_poc_challenge_proto_init()
	md_PoCChallenge = File_inference_inference_poc_challenge_proto.Messages().ByName("PoCChallenge")
	fd_PoCChallenge_epoch_index = md_PoCChallenge.Fields().ByName("epoch_index")
	fd_PoCChallenge_challenger = md_PoCChallenge.Fields().ByName("challenger")
	fd_PoCChallenge_target = md_PoCChallenge.Fields().ByName("target")
	fd_PoCChallenge_expected_reward = md_PoCChallenge.Fields().ByName("expected_reward")
	fd_PoCChallenge_locked_payment = md_PoCChallenge.Fields().ByName("locked_payment")
	fd_PoCChallenge_start_height = md_PoCChallenge.Fields().ByName("start_height")
	fd_PoCChallenge_seed = md_PoCChallenge.Fields().ByName("seed")
	fd_PoCChallenge_state = md_PoCChallenge.Fields().ByName("state")
}

var _ protoreflect.Message = (*fastReflection_PoCChallenge)(nil)

type fastReflection_PoCChallenge PoCChallenge

func (x *PoCChallenge) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PoCChallenge)(x)
}

func (x *PoCChallenge) slowProtoReflect() protoreflect.Message {
	mi := &file_inference_inference_poc_challenge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PoCChallenge_messageType fastReflection_PoCChallenge_messageType
var _ protoreflect.MessageType = fastReflection_PoCChallenge_messageType{}

type fastReflection_PoCChallenge_messageType struct{}

func (x fastReflection_PoCChallenge_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PoCChallenge)(nil)
}
func (x fastReflection_PoCChallenge_messageType) New() protoreflect.Message {
	return new(fastReflection_PoCChallenge)
}
func (x fastReflection_PoCChallenge_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PoCChallenge
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PoCChallenge) Descriptor() protoreflect.MessageDescriptor {
	return md_PoCChallenge
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PoCChallenge) Type() protoreflect.MessageType {
	return _fastReflection_PoCChallenge_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PoCChallenge) New() protoreflect.Message {
	return new(fastReflection_PoCChallenge)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PoCChallenge) Interface() protoreflect.ProtoMessage {
	return (*PoCChallenge)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PoCChallenge) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.EpochIndex != uint64(0) {
		value := protoreflect.ValueOfUint64(x.EpochIndex)
		if !f(fd_PoCChallenge_epoch_index, value) {
			return
		}
	}
	if x.Challenger != "" {
		value := protoreflect.ValueOfString(x.Challenger)
		if !f(fd_PoCChallenge_challenger, value) {
			return
		}
	}
	if x.Target != "" {
		value := protoreflect.ValueOfString(x.Target)
		if !f(fd_PoCChallenge_target, value) {
			return
		}
	}
	if x.ExpectedReward != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ExpectedReward)
		if !f(fd_PoCChallenge_expected_reward, value) {
			return
		}
	}
	if x.LockedPayment != uint64(0) {
		value := protoreflect.ValueOfUint64(x.LockedPayment)
		if !f(fd_PoCChallenge_locked_payment, value) {
			return
		}
	}
	if x.StartHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.StartHeight)
		if !f(fd_PoCChallenge_start_height, value) {
			return
		}
	}
	if len(x.Seed) != 0 {
		value := protoreflect.ValueOfBytes(x.Seed)
		if !f(fd_PoCChallenge_seed, value) {
			return
		}
	}
	if x.State != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.State))
		if !f(fd_PoCChallenge_state, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PoCChallenge) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "inference.inference.PoCChallenge.epoch_index":
		return x.EpochIndex != uint64(0)
	case "inference.inference.PoCChallenge.challenger":
		return x.Challenger != ""
	case "inference.inference.PoCChallenge.target":
		return x.Target != ""
	case "inference.inference.PoCChallenge.expected_reward":
		return x.ExpectedReward != uint64(0)
	case "inference.inference.PoCChallenge.locked_payment":
		return x.LockedPayment != uint64(0)
	case "inference.inference.PoCChallenge.start_height":
		return x.StartHeight != int64(0)
	case "inference.inference.PoCChallenge.seed":
		return len(x.Seed) != 0
	case "inference.inference.PoCChallenge.state":
		return x.State != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.PoCChallenge does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCChallenge) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "inference.inference.PoCChallenge.epoch_index":
		x.EpochIndex = uint64(0)
	case "inference.inference.PoCChallenge.challenger":
		x.Challenger = ""
	case "inference.inference.PoCChallenge.target":
		x.Target = ""
	case "inference.inference.PoCChallenge.expected_reward":
		x.ExpectedReward = uint64(0)
	case "inference.inference.PoCChallenge.locked_payment":
		x.LockedPayment = uint64(0)
	case "inference.inference.PoCChallenge.start_height":
		x.StartHeight = int64(0)
	case "inference.inference.PoCChallenge.seed":
		x.Seed = nil
	case "inference.inference.PoCChallenge.state":
		x.State = 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.PoCChallenge does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PoCChallenge) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "inference.inference.PoCChallenge.epoch_index":
		value := x.EpochIndex
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.PoCChallenge.challenger":
		value := x.Challenger
		return protoreflect.ValueOfString(value)
	case "inference.inference.PoCChallenge.target":
		value := x.Target
		return protoreflect.ValueOfString(value)
	case "inference.inference.PoCChallenge.expected_reward":
		value := x.ExpectedReward
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.PoCChallenge.locked_payment":
		value := x.LockedPayment
		return protoreflect.ValueOfUint64(value)
	case "inference.inference.PoCChallenge.start_height":
		value := x.StartHeight
		return protoreflect.ValueOfInt64(value)
	case "inference.inference.PoCChallenge.seed":
		value := x.Seed
		return protoreflect.ValueOfBytes(value)
	case "inference.inference.PoCChallenge.state":
		value := x.State
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.PoCChallenge does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCChallenge) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "inference.inference.PoCChallenge.epoch_index":
		x.EpochIndex = value.Uint()
	case "inference.inference.PoCChallenge.challenger":
		x.Challenger = value.Interface().(string)
	case "inference.inference.PoCChallenge.target":
		x.Target = value.Interface().(string)
	case "inference.inference.PoCChallenge.expected_reward":
		x.ExpectedReward = value.Uint()
	case "inference.inference.PoCChallenge.locked_payment":
		x.LockedPayment = value.Uint()
	case "inference.inference.PoCChallenge.start_height":
		x.StartHeight = value.Int()
	case "inference.inference.PoCChallenge.seed":
		x.Seed = value.Bytes()
	case "inference.inference.PoCChallenge.state":
		x.State = (PoCChallengeState)(value.Enum())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.PoCChallenge does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCChallenge) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.PoCChallenge.epoch_index":
		panic(fmt.Errorf("field epoch_index of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.challenger":
		panic(fmt.Errorf("field challenger of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.target":
		panic(fmt.Errorf("field target of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.expected_reward":
		panic(fmt.Errorf("field expected_reward of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.locked_payment":
		panic(fmt.Errorf("field locked_payment of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.start_height":
		panic(fmt.Errorf("field start_height of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.seed":
		panic(fmt.Errorf("field seed of message inference.inference.PoCChallenge is not mutable"))
	case "inference.inference.PoCChallenge.state":
		panic(fmt.Errorf("field state of message inference.inference.PoCChallenge is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.PoCChallenge does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PoCChallenge) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.PoCChallenge.epoch_index":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.PoCChallenge.challenger":
		return protoreflect.ValueOfString("")
	case "inference.inference.PoCChallenge.target":
		return protoreflect.ValueOfString("")
	case "inference.inference.PoCChallenge.expected_reward":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.PoCChallenge.locked_payment":
		return protoreflect.ValueOfUint64(uint64(0))
	case "inference.inference.PoCChallenge.start_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "inference.inference.PoCChallenge.seed":
		return protoreflect.ValueOfBytes(nil)
	case "inference.inference.PoCChallenge.state":
		return protoreflect.ValueOfEnum(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.PoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.PoCChallenge does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PoCChallenge) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in inference.inference.PoCChallenge", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PoCChallenge) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoCChallenge) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PoCChallenge) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PoCChallenge) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PoCChallenge)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.EpochIndex != 0 {
			n += 1 + runtime.Sov(uint64(x.EpochIndex))
		}
		l = len(x.Challenger)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Target)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ExpectedReward != 0 {
			n += 1 + runtime.Sov(uint64(x.ExpectedReward))
		}
		if x.LockedPayment != 0 {
			n += 1 + runtime.Sov(uint64(x.LockedPayment))
		}
		if x.StartHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.StartHeight))
		}
		l = len(x.Seed)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.State != 0 {
			n += 1 + runtime.Sov(uint64(x.State))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PoCChallenge)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.State != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.State))
			i--
			dAtA[i] = 0x40
		}
		if len(x.Seed) > 0 {
			i -= len(x.Seed)
			copy(dAtA[i:], x.Seed)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Seed)))
			i--
			dAtA[i] = 0x3a
		}
		if x.StartHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.StartHeight))
			i--
			dAtA[i] = 0x30
		}
		if x.LockedPayment != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.LockedPayment))
			i--
			dAtA[i] = 0x28
		}
		if x.ExpectedReward != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ExpectedReward))
			i--
			dAtA[i] = 0x20
		}
		if len(x.Target) > 0 {
			i -= len(x.Target)
			copy(dAtA[i:], x.Target)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Target)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Challenger) > 0 {
			i -= len(x.Challenger)
			copy(dAtA[i:], x.Challenger)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Challenger)))
			i--
			dAtA[i] = 0x12
		}
		if x.EpochIndex != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EpochIndex))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PoCChallenge)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PoCChallenge: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PoCChallenge: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EpochIndex", wireType)
				}
				x.EpochIndex = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EpochIndex |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Challenger = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Target = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ExpectedReward", wireType)
				}
				x.ExpectedReward = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ExpectedReward |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LockedPayment", wireType)
				}
				x.LockedPayment = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.LockedPayment |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
				}
				x.StartHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.StartHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Seed = append(x.Seed[:0], dAtA[iNdEx:postIndex]...)
				if x.Seed == nil {
					x.Seed = []byte{}
				}
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
				}
				x.State = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.State |= PoCChallengeState(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_OpenPoCChallenge_4_list)(nil)

type _OpenPoCChallenge_4_list struct {
	list *[]*PoCV2StoreCommit
}

func (x *_OpenPoCChallenge_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_OpenPoCChallenge_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_OpenPoCChallenge_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*PoCV2StoreCommit)
	(*x.list)[i] = concreteValue
}

func (x *_OpenPoCChallenge_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*PoCV2StoreCommit)
	*x.list = append(*x.list, concreteValue)
}

func (x *_OpenPoCChallenge_4_list) AppendMutable() protoreflect.Value {
	v := new(PoCV2StoreCommit)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_OpenPoCChallenge_4_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_OpenPoCChallenge_4_list) NewElement() protoreflect.Value {
	v := new(PoCV2StoreCommit)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_OpenPoCChallenge_4_list) IsValid() bool {
	return x.list != nil
}

var (
	md_OpenPoCChallenge            protoreflect.MessageDescriptor
	fd_OpenPoCChallenge_challenge  protoreflect.FieldDescriptor
	fd_OpenPoCChallenge_finish     protoreflect.FieldDescriptor
	fd_OpenPoCChallenge_generating protoreflect.FieldDescriptor
	fd_OpenPoCChallenge_commits    protoreflect.FieldDescriptor
)

func init() {
	file_inference_inference_poc_challenge_proto_init()
	md_OpenPoCChallenge = File_inference_inference_poc_challenge_proto.Messages().ByName("OpenPoCChallenge")
	fd_OpenPoCChallenge_challenge = md_OpenPoCChallenge.Fields().ByName("challenge")
	fd_OpenPoCChallenge_finish = md_OpenPoCChallenge.Fields().ByName("finish")
	fd_OpenPoCChallenge_generating = md_OpenPoCChallenge.Fields().ByName("generating")
	fd_OpenPoCChallenge_commits = md_OpenPoCChallenge.Fields().ByName("commits")
}

var _ protoreflect.Message = (*fastReflection_OpenPoCChallenge)(nil)

type fastReflection_OpenPoCChallenge OpenPoCChallenge

func (x *OpenPoCChallenge) ProtoReflect() protoreflect.Message {
	return (*fastReflection_OpenPoCChallenge)(x)
}

func (x *OpenPoCChallenge) slowProtoReflect() protoreflect.Message {
	mi := &file_inference_inference_poc_challenge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_OpenPoCChallenge_messageType fastReflection_OpenPoCChallenge_messageType
var _ protoreflect.MessageType = fastReflection_OpenPoCChallenge_messageType{}

type fastReflection_OpenPoCChallenge_messageType struct{}

func (x fastReflection_OpenPoCChallenge_messageType) Zero() protoreflect.Message {
	return (*fastReflection_OpenPoCChallenge)(nil)
}
func (x fastReflection_OpenPoCChallenge_messageType) New() protoreflect.Message {
	return new(fastReflection_OpenPoCChallenge)
}
func (x fastReflection_OpenPoCChallenge_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_OpenPoCChallenge
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_OpenPoCChallenge) Descriptor() protoreflect.MessageDescriptor {
	return md_OpenPoCChallenge
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_OpenPoCChallenge) Type() protoreflect.MessageType {
	return _fastReflection_OpenPoCChallenge_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_OpenPoCChallenge) New() protoreflect.Message {
	return new(fastReflection_OpenPoCChallenge)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_OpenPoCChallenge) Interface() protoreflect.ProtoMessage {
	return (*OpenPoCChallenge)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_OpenPoCChallenge) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Challenge != nil {
		value := protoreflect.ValueOfMessage(x.Challenge.ProtoReflect())
		if !f(fd_OpenPoCChallenge_challenge, value) {
			return
		}
	}
	if x.Finish != int64(0) {
		value := protoreflect.ValueOfInt64(x.Finish)
		if !f(fd_OpenPoCChallenge_finish, value) {
			return
		}
	}
	if x.Generating != false {
		value := protoreflect.ValueOfBool(x.Generating)
		if !f(fd_OpenPoCChallenge_generating, value) {
			return
		}
	}
	if len(x.Commits) != 0 {
		value := protoreflect.ValueOfList(&_OpenPoCChallenge_4_list{list: &x.Commits})
		if !f(fd_OpenPoCChallenge_commits, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_OpenPoCChallenge) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "inference.inference.OpenPoCChallenge.challenge":
		return x.Challenge != nil
	case "inference.inference.OpenPoCChallenge.finish":
		return x.Finish != int64(0)
	case "inference.inference.OpenPoCChallenge.generating":
		return x.Generating != false
	case "inference.inference.OpenPoCChallenge.commits":
		return len(x.Commits) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.OpenPoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.OpenPoCChallenge does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OpenPoCChallenge) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "inference.inference.OpenPoCChallenge.challenge":
		x.Challenge = nil
	case "inference.inference.OpenPoCChallenge.finish":
		x.Finish = int64(0)
	case "inference.inference.OpenPoCChallenge.generating":
		x.Generating = false
	case "inference.inference.OpenPoCChallenge.commits":
		x.Commits = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.OpenPoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.OpenPoCChallenge does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_OpenPoCChallenge) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "inference.inference.OpenPoCChallenge.challenge":
		value := x.Challenge
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "inference.inference.OpenPoCChallenge.finish":
		value := x.Finish
		return protoreflect.ValueOfInt64(value)
	case "inference.inference.OpenPoCChallenge.generating":
		value := x.Generating
		return protoreflect.ValueOfBool(value)
	case "inference.inference.OpenPoCChallenge.commits":
		if len(x.Commits) == 0 {
			return protoreflect.ValueOfList(&_OpenPoCChallenge_4_list{})
		}
		listValue := &_OpenPoCChallenge_4_list{list: &x.Commits}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.OpenPoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.OpenPoCChallenge does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OpenPoCChallenge) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "inference.inference.OpenPoCChallenge.challenge":
		x.Challenge = value.Message().Interface().(*PoCChallenge)
	case "inference.inference.OpenPoCChallenge.finish":
		x.Finish = value.Int()
	case "inference.inference.OpenPoCChallenge.generating":
		x.Generating = value.Bool()
	case "inference.inference.OpenPoCChallenge.commits":
		lv := value.List()
		clv := lv.(*_OpenPoCChallenge_4_list)
		x.Commits = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.OpenPoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.OpenPoCChallenge does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OpenPoCChallenge) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.OpenPoCChallenge.challenge":
		if x.Challenge == nil {
			x.Challenge = new(PoCChallenge)
		}
		return protoreflect.ValueOfMessage(x.Challenge.ProtoReflect())
	case "inference.inference.OpenPoCChallenge.commits":
		if x.Commits == nil {
			x.Commits = []*PoCV2StoreCommit{}
		}
		value := &_OpenPoCChallenge_4_list{list: &x.Commits}
		return protoreflect.ValueOfList(value)
	case "inference.inference.OpenPoCChallenge.finish":
		panic(fmt.Errorf("field finish of message inference.inference.OpenPoCChallenge is not mutable"))
	case "inference.inference.OpenPoCChallenge.generating":
		panic(fmt.Errorf("field generating of message inference.inference.OpenPoCChallenge is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.OpenPoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.OpenPoCChallenge does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_OpenPoCChallenge) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.OpenPoCChallenge.challenge":
		m := new(PoCChallenge)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "inference.inference.OpenPoCChallenge.finish":
		return protoreflect.ValueOfInt64(int64(0))
	case "inference.inference.OpenPoCChallenge.generating":
		return protoreflect.ValueOfBool(false)
	case "inference.inference.OpenPoCChallenge.commits":
		list := []*PoCV2StoreCommit{}
		return protoreflect.ValueOfList(&_OpenPoCChallenge_4_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.OpenPoCChallenge"))
		}
		panic(fmt.Errorf("message inference.inference.OpenPoCChallenge does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_OpenPoCChallenge) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in inference.inference.OpenPoCChallenge", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_OpenPoCChallenge) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_OpenPoCChallenge) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_OpenPoCChallenge) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_OpenPoCChallenge) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*OpenPoCChallenge)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Challenge != nil {
			l = options.Size(x.Challenge)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Finish != 0 {
			n += 1 + runtime.Sov(uint64(x.Finish))
		}
		if x.Generating {
			n += 2
		}
		if len(x.Commits) > 0 {
			for _, e := range x.Commits {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*OpenPoCChallenge)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Commits) > 0 {
			for iNdEx := len(x.Commits) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Commits[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x22
			}
		}
		if x.Generating {
			i--
			if x.Generating {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x18
		}
		if x.Finish != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Finish))
			i--
			dAtA[i] = 0x10
		}
		if x.Challenge != nil {
			encoded, err := options.Marshal(x.Challenge)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*OpenPoCChallenge)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: OpenPoCChallenge: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: OpenPoCChallenge: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Challenge", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Challenge == nil {
					x.Challenge = &PoCChallenge{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Challenge); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Finish", wireType)
				}
				x.Finish = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Finish |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Generating", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Generating = bool(v != 0)
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Commits", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Commits = append(x.Commits, &PoCV2StoreCommit{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Commits[len(x.Commits)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: inference/inference/poc_challenge.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoCChallengeState int32

const (
	PoCChallengeState_POC_CHALLENGE_STATE_OPEN             PoCChallengeState = 0
	PoCChallengeState_POC_CHALLENGE_STATE_CHALLENGE_FAILED PoCChallengeState = 1
	PoCChallengeState_POC_CHALLENGE_STATE_ABORTED          PoCChallengeState = 2
	PoCChallengeState_POC_CHALLENGE_STATE_PASSED           PoCChallengeState = 3
)

// Enum value maps for PoCChallengeState.
var (
	PoCChallengeState_name = map[int32]string{
		0: "POC_CHALLENGE_STATE_OPEN",
		1: "POC_CHALLENGE_STATE_CHALLENGE_FAILED",
		2: "POC_CHALLENGE_STATE_ABORTED",
		3: "POC_CHALLENGE_STATE_PASSED",
	}
	PoCChallengeState_value = map[string]int32{
		"POC_CHALLENGE_STATE_OPEN":             0,
		"POC_CHALLENGE_STATE_CHALLENGE_FAILED": 1,
		"POC_CHALLENGE_STATE_ABORTED":          2,
		"POC_CHALLENGE_STATE_PASSED":           3,
	}
)

func (x PoCChallengeState) Enum() *PoCChallengeState {
	p := new(PoCChallengeState)
	*p = x
	return p
}

func (x PoCChallengeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoCChallengeState) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_inference_poc_challenge_proto_enumTypes[0].Descriptor()
}

func (PoCChallengeState) Type() protoreflect.EnumType {
	return &file_inference_inference_poc_challenge_proto_enumTypes[0]
}

func (x PoCChallengeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoCChallengeState.Descriptor instead.
func (PoCChallengeState) EnumDescriptor() ([]byte, []int) {
	return file_inference_inference_poc_challenge_proto_rawDescGZIP(), []int{0}
}

type PoCChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EpochIndex     uint64            `protobuf:"varint,1,opt,name=epoch_index,json=epochIndex,proto3" json:"epoch_index,omitempty"`
	Challenger     string            `protobuf:"bytes,2,opt,name=challenger,proto3" json:"challenger,omitempty"`
	Target         string            `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	ExpectedReward uint64            `protobuf:"varint,4,opt,name=expected_reward,json=expectedReward,proto3" json:"expected_reward,omitempty"`
	LockedPayment  uint64            `protobuf:"varint,5,opt,name=locked_payment,json=lockedPayment,proto3" json:"locked_payment,omitempty"`
	StartHeight    int64             `protobuf:"varint,6,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	Seed           []byte            `protobuf:"bytes,7,opt,name=seed,proto3" json:"seed,omitempty"`
	State          PoCChallengeState `protobuf:"varint,8,opt,name=state,proto3,enum=inference.inference.PoCChallengeState" json:"state,omitempty"`
}

func (x *PoCChallenge) Reset() {
	*x = PoCChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inference_inference_poc_challenge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoCChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoCChallenge) ProtoMessage() {}

// Deprecated: Use PoCChallenge.ProtoReflect.Descriptor instead.
func (*PoCChallenge) Descriptor() ([]byte, []int) {
	return file_inference_inference_poc_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *PoCChallenge) GetEpochIndex() uint64 {
	if x != nil {
		return x.EpochIndex
	}
	return 0
}

func (x *PoCChallenge) GetChallenger() string {
	if x != nil {
		return x.Challenger
	}
	return ""
}

func (x *PoCChallenge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PoCChallenge) GetExpectedReward() uint64 {
	if x != nil {
		return x.ExpectedReward
	}
	return 0
}

func (x *PoCChallenge) GetLockedPayment() uint64 {
	if x != nil {
		return x.LockedPayment
	}
	return 0
}

func (x *PoCChallenge) GetStartHeight() int64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *PoCChallenge) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *PoCChallenge) GetState() PoCChallengeState {
	if x != nil {
		return x.State
	}
	return PoCChallengeState_POC_CHALLENGE_STATE_OPEN
}

type OpenPoCChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge  *PoCChallenge       `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Finish     int64               `protobuf:"varint,2,opt,name=finish,proto3" json:"finish,omitempty"`
	Generating bool                `protobuf:"varint,3,opt,name=generating,proto3" json:"generating,omitempty"`
	Commits    []*PoCV2StoreCommit `protobuf:"bytes,4,rep,name=commits,proto3" json:"commits,omitempty"`
}

func (x *OpenPoCChallenge) Reset() {
	*x = OpenPoCChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inference_inference_poc_challenge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenPoCChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPoCChallenge) ProtoMessage() {}

// Deprecated: Use OpenPoCChallenge.ProtoReflect.Descriptor instead.
func (*OpenPoCChallenge) Descriptor() ([]byte, []int) {
	return file_inference_inference_poc_challenge_proto_rawDescGZIP(), []int{1}
}

func (x *OpenPoCChallenge) GetChallenge() *PoCChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *OpenPoCChallenge) GetFinish() int64 {
	if x != nil {
		return x.Finish
	}
	return 0
}

func (x *OpenPoCChallenge) GetGenerating() bool {
	if x != nil {
		return x.Generating
	}
	return false
}

func (x *OpenPoCChallenge) GetCommits() []*PoCV2StoreCommit {
	if x != nil {
		return x.Commits
	}
	return nil
}

var File_inference_inference_poc_challenge_proto protoreflect.FileDescriptor

var file_inference_inference_poc_challenge_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x6f, 0x63, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x20,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2f, 0x70, 0x6f, 0x63, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xac, 0x02, 0x0a, 0x0c, 0x50, 0x6f, 0x43, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65,
	0x64, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x26, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x43, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0xcc, 0x01, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6f, 0x43, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x6f,
	0x43, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x1e, 0x0a,
	0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x3f, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x43, 0x56, 0x32, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x2a, 0x9c,
	0x01, 0x0a, 0x11, 0x50, 0x6f, 0x43, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4f, 0x43, 0x5f, 0x43, 0x48, 0x41, 0x4c,
	0x4c, 0x45, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e,
	0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x50, 0x4f, 0x43, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45,
	0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45,
	0x4e, 0x47, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b,
	0x50, 0x4f, 0x43, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1e, 0x0a,
	0x1a, 0x50, 0x4f, 0x43, 0x5f, 0x43, 0x48, 0x41, 0x4c, 0x4c, 0x45, 0x4e, 0x47, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x45, 0x44, 0x10, 0x03, 0x42, 0xbf, 0x01,
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x11, 0x50, 0x6f, 0x63, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x49, 0x49, 0x58, 0xaa, 0x02, 0x13, 0x49, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0xca, 0x02, 0x13, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x49, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xe2, 0x02, 0x1f, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5c, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x49, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x3a, 0x3a, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inference_inference_poc_challenge_proto_rawDescOnce sync.Once
	file_inference_inference_poc_challenge_proto_rawDescData = file_inference_inference_poc_challenge_proto_rawDesc
)

func file_inference_inference_poc_challenge_proto_rawDescGZIP() []byte {
	file_inference_inference_poc_challenge_proto_rawDescOnce.Do(func() {
		file_inference_inference_poc_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(file_inference_inference_poc_challenge_proto_rawDescData)
	})
	return file_inference_inference_poc_challenge_proto_rawDescData
}

var file_inference_inference_poc_challenge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_inference_poc_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inference_inference_poc_challenge_proto_goTypes = []interface{}{
	(PoCChallengeState)(0),   // 0: inference.inference.PoCChallengeState
	(*PoCChallenge)(nil),     // 1: inference.inference.PoCChallenge
	(*OpenPoCChallenge)(nil), // 2: inference.inference.OpenPoCChallenge
	(*PoCV2StoreCommit)(nil), // 3: inference.inference.PoCV2StoreCommit
}
var file_inference_inference_poc_challenge_proto_depIdxs = []int32{
	0, // 0: inference.inference.PoCChallenge.state:type_name -> inference.inference.PoCChallengeState
	1, // 1: inference.inference.OpenPoCChallenge.challenge:type_name -> inference.inference.PoCChallenge
	3, // 2: inference.inference.OpenPoCChallenge.commits:type_name -> inference.inference.PoCV2StoreCommit
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_inference_inference_poc_challenge_proto_init() }
func file_inference_inference_poc_challenge_proto_init() {
	if File_inference_inference_poc_challenge_proto != nil {
		return
	}
	file_inference_inference_poc_v2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_inference_inference_poc_challenge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoCChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inference_inference_poc_challenge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenPoCChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inference_inference_poc_challenge_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inference_inference_poc_challenge_proto_goTypes,
		DependencyIndexes: file_inference_inference_poc_challenge_proto_depIdxs,
		EnumInfos:         file_inference_inference_poc_challenge_proto_enumTypes,
		MessageInfos:      file_inference_inference_poc_challenge_proto_msgTypes,
	}.Build()
	File_inference_inference_poc_challenge_proto = out.File
	file_inference_inference_poc_challenge_proto_rawDesc = nil
	file_inference_inference_poc_challenge_proto_goTypes = nil
	file_inference_inference_poc_challenge_proto_depIdxs = nil
}
