// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package inference

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_SPRTPrecomputedValues                       protoreflect.MessageDescriptor
	fd_SPRTPrecomputedValues_invalidation_log_fail protoreflect.FieldDescriptor
	fd_SPRTPrecomputedValues_invalidation_log_pass protoreflect.FieldDescriptor
	fd_SPRTPrecomputedValues_inactive_log_fail     protoreflect.FieldDescriptor
	fd_SPRTPrecomputedValues_inactive_log_pass     protoreflect.FieldDescriptor
)

func init() {
	file_inference_inference_sprt_proto_init()
	md_SPRTPrecomputedValues = File_inference_inference_sprt_proto.Messages().ByName("SPRTPrecomputedValues")
	fd_SPRTPrecomputedValues_invalidation_log_fail = md_SPRTPrecomputedValues.Fields().ByName("invalidation_log_fail")
	fd_SPRTPrecomputedValues_invalidation_log_pass = md_SPRTPrecomputedValues.Fields().ByName("invalidation_log_pass")
	fd_SPRTPrecomputedValues_inactive_log_fail = md_SPRTPrecomputedValues.Fields().ByName("inactive_log_fail")
	fd_SPRTPrecomputedValues_inactive_log_pass = md_SPRTPrecomputedValues.Fields().ByName("inactive_log_pass")
}

var _ protoreflect.Message = (*fastReflection_SPRTPrecomputedValues)(nil)

type fastReflection_SPRTPrecomputedValues SPRTPrecomputedValues

func (x *SPRTPrecomputedValues) ProtoReflect() protoreflect.Message {
	return (*fastReflection_SPRTPrecomputedValues)(x)
}

func (x *SPRTPrecomputedValues) slowProtoReflect() protoreflect.Message {
	mi := &file_inference_inference_sprt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_SPRTPrecomputedValues_messageType fastReflection_SPRTPrecomputedValues_messageType
var _ protoreflect.MessageType = fastReflection_SPRTPrecomputedValues_messageType{}

type fastReflection_SPRTPrecomputedValues_messageType struct{}

func (x fastReflection_SPRTPrecomputedValues_messageType) Zero() protoreflect.Message {
	return (*fastReflection_SPRTPrecomputedValues)(nil)
}
func (x fastReflection_SPRTPrecomputedValues_messageType) New() protoreflect.Message {
	return new(fastReflection_SPRTPrecomputedValues)
}
func (x fastReflection_SPRTPrecomputedValues_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_SPRTPrecomputedValues
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_SPRTPrecomputedValues) Descriptor() protoreflect.MessageDescriptor {
	return md_SPRTPrecomputedValues
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_SPRTPrecomputedValues) Type() protoreflect.MessageType {
	return _fastReflection_SPRTPrecomputedValues_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_SPRTPrecomputedValues) New() protoreflect.Message {
	return new(fastReflection_SPRTPrecomputedValues)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_SPRTPrecomputedValues) Interface() protoreflect.ProtoMessage {
	return (*SPRTPrecomputedValues)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_SPRTPrecomputedValues) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.InvalidationLogFail != nil {
		value := protoreflect.ValueOfMessage(x.InvalidationLogFail.ProtoReflect())
		if !f(fd_SPRTPrecomputedValues_invalidation_log_fail, value) {
			return
		}
	}
	if x.InvalidationLogPass != nil {
		value := protoreflect.ValueOfMessage(x.InvalidationLogPass.ProtoReflect())
		if !f(fd_SPRTPrecomputedValues_invalidation_log_pass, value) {
			return
		}
	}
	if x.InactiveLogFail != nil {
		value := protoreflect.ValueOfMessage(x.InactiveLogFail.ProtoReflect())
		if !f(fd_SPRTPrecomputedValues_inactive_log_fail, value) {
			return
		}
	}
	if x.InactiveLogPass != nil {
		value := protoreflect.ValueOfMessage(x.InactiveLogPass.ProtoReflect())
		if !f(fd_SPRTPrecomputedValues_inactive_log_pass, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_SPRTPrecomputedValues) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_fail":
		return x.InvalidationLogFail != nil
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_pass":
		return x.InvalidationLogPass != nil
	case "inference.inference.SPRTPrecomputedValues.inactive_log_fail":
		return x.InactiveLogFail != nil
	case "inference.inference.SPRTPrecomputedValues.inactive_log_pass":
		return x.InactiveLogPass != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.SPRTPrecomputedValues"))
		}
		panic(fmt.Errorf("message inference.inference.SPRTPrecomputedValues does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SPRTPrecomputedValues) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_fail":
		x.InvalidationLogFail = nil
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_pass":
		x.InvalidationLogPass = nil
	case "inference.inference.SPRTPrecomputedValues.inactive_log_fail":
		x.InactiveLogFail = nil
	case "inference.inference.SPRTPrecomputedValues.inactive_log_pass":
		x.InactiveLogPass = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.SPRTPrecomputedValues"))
		}
		panic(fmt.Errorf("message inference.inference.SPRTPrecomputedValues does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_SPRTPrecomputedValues) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_fail":
		value := x.InvalidationLogFail
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_pass":
		value := x.InvalidationLogPass
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.inactive_log_fail":
		value := x.InactiveLogFail
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.inactive_log_pass":
		value := x.InactiveLogPass
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.SPRTPrecomputedValues"))
		}
		panic(fmt.Errorf("message inference.inference.SPRTPrecomputedValues does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SPRTPrecomputedValues) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_fail":
		x.InvalidationLogFail = value.Message().Interface().(*Decimal)
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_pass":
		x.InvalidationLogPass = value.Message().Interface().(*Decimal)
	case "inference.inference.SPRTPrecomputedValues.inactive_log_fail":
		x.InactiveLogFail = value.Message().Interface().(*Decimal)
	case "inference.inference.SPRTPrecomputedValues.inactive_log_pass":
		x.InactiveLogPass = value.Message().Interface().(*Decimal)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.SPRTPrecomputedValues"))
		}
		panic(fmt.Errorf("message inference.inference.SPRTPrecomputedValues does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SPRTPrecomputedValues) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_fail":
		if x.InvalidationLogFail == nil {
			x.InvalidationLogFail = new(Decimal)
		}
		return protoreflect.ValueOfMessage(x.InvalidationLogFail.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_pass":
		if x.InvalidationLogPass == nil {
			x.InvalidationLogPass = new(Decimal)
		}
		return protoreflect.ValueOfMessage(x.InvalidationLogPass.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.inactive_log_fail":
		if x.InactiveLogFail == nil {
			x.InactiveLogFail = new(Decimal)
		}
		return protoreflect.ValueOfMessage(x.InactiveLogFail.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.inactive_log_pass":
		if x.InactiveLogPass == nil {
			x.InactiveLogPass = new(Decimal)
		}
		return protoreflect.ValueOfMessage(x.InactiveLogPass.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.SPRTPrecomputedValues"))
		}
		panic(fmt.Errorf("message inference.inference.SPRTPrecomputedValues does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_SPRTPrecomputedValues) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_fail":
		m := new(Decimal)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.invalidation_log_pass":
		m := new(Decimal)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.inactive_log_fail":
		m := new(Decimal)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "inference.inference.SPRTPrecomputedValues.inactive_log_pass":
		m := new(Decimal)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: inference.inference.SPRTPrecomputedValues"))
		}
		panic(fmt.Errorf("message inference.inference.SPRTPrecomputedValues does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_SPRTPrecomputedValues) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in inference.inference.SPRTPrecomputedValues", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_SPRTPrecomputedValues) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SPRTPrecomputedValues) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_SPRTPrecomputedValues) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_SPRTPrecomputedValues) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*SPRTPrecomputedValues)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.InvalidationLogFail != nil {
			l = options.Size(x.InvalidationLogFail)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.InvalidationLogPass != nil {
			l = options.Size(x.InvalidationLogPass)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.InactiveLogFail != nil {
			l = options.Size(x.InactiveLogFail)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.InactiveLogPass != nil {
			l = options.Size(x.InactiveLogPass)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*SPRTPrecomputedValues)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.InactiveLogPass != nil {
			encoded, err := options.Marshal(x.InactiveLogPass)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x22
		}
		if x.InactiveLogFail != nil {
			encoded, err := options.Marshal(x.InactiveLogFail)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x1a
		}
		if x.InvalidationLogPass != nil {
			encoded, err := options.Marshal(x.InvalidationLogPass)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x12
		}
		if x.InvalidationLogFail != nil {
			encoded, err := options.Marshal(x.InvalidationLogFail)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*SPRTPrecomputedValues)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: SPRTPrecomputedValues: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: SPRTPrecomputedValues: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InvalidationLogFail", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.InvalidationLogFail == nil {
					x.InvalidationLogFail = &Decimal{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.InvalidationLogFail); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InvalidationLogPass", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.InvalidationLogPass == nil {
					x.InvalidationLogPass = &Decimal{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.InvalidationLogPass); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InactiveLogFail", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.InactiveLogFail == nil {
					x.InactiveLogFail = &Decimal{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.InactiveLogFail); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InactiveLogPass", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.InactiveLogPass == nil {
					x.InactiveLogPass = &Decimal{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.InactiveLogPass); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: inference/inference/sprt.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SPRTPrecomputedValues contains log-likelihood ratios precomputed for SPRT.
type SPRTPrecomputedValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvalidationLogFail *Decimal `protobuf:"bytes,1,opt,name=invalidation_log_fail,json=invalidationLogFail,proto3" json:"invalidation_log_fail,omitempty"`
	InvalidationLogPass *Decimal `protobuf:"bytes,2,opt,name=invalidation_log_pass,json=invalidationLogPass,proto3" json:"invalidation_log_pass,omitempty"`
	InactiveLogFail     *Decimal `protobuf:"bytes,3,opt,name=inactive_log_fail,json=inactiveLogFail,proto3" json:"inactive_log_fail,omitempty"`
	InactiveLogPass     *Decimal `protobuf:"bytes,4,opt,name=inactive_log_pass,json=inactiveLogPass,proto3" json:"inactive_log_pass,omitempty"`
}

func (x *SPRTPrecomputedValues) Reset() {
	*x = SPRTPrecomputedValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inference_inference_sprt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPRTPrecomputedValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPRTPrecomputedValues) ProtoMessage() {}

// Deprecated: Use SPRTPrecomputedValues.ProtoReflect.Descriptor instead.
func (*SPRTPrecomputedValues) Descriptor() ([]byte, []int) {
	return file_inference_inference_sprt_proto_rawDescGZIP(), []int{0}
}

func (x *SPRTPrecomputedValues) GetInvalidationLogFail() *Decimal {
	if x != nil {
		return x.InvalidationLogFail
	}
	return nil
}

func (x *SPRTPrecomputedValues) GetInvalidationLogPass() *Decimal {
	if x != nil {
		return x.InvalidationLogPass
	}
	return nil
}

func (x *SPRTPrecomputedValues) GetInactiveLogFail() *Decimal {
	if x != nil {
		return x.InactiveLogFail
	}
	return nil
}

func (x *SPRTPrecomputedValues) GetInactiveLogPass() *Decimal {
	if x != nil {
		return x.InactiveLogPass
	}
	return nil
}

var File_inference_inference_sprt_proto protoreflect.FileDescriptor

var file_inference_inference_sprt_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x73, 0x70, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x02,
	0x0a, 0x15, 0x53, 0x50, 0x52, 0x54, 0x50, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x15, 0x69, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x66, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x52, 0x13, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x46, 0x61, 0x69, 0x6c, 0x12, 0x50, 0x0a, 0x15, 0x69, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x44,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x13, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x73, 0x73, 0x12, 0x48, 0x0a, 0x11, 0x69,
	0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x66, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x52, 0x0f, 0x69, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x6f,
	0x67, 0x46, 0x61, 0x69, 0x6c, 0x12, 0x48, 0x0a, 0x11, 0x69, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x0f,
	0x69, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x50, 0x61, 0x73, 0x73, 0x3a,
	0x04, 0xe8, 0xa0, 0x1f, 0x01, 0x42, 0xb7, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x42, 0x09, 0x53, 0x70, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x49, 0x49, 0x58, 0xaa, 0x02, 0x13, 0x49, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0xca, 0x02, 0x13, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x49, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0xe2, 0x02, 0x1f, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5c, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x14, 0x49, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x3a, 0x3a, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inference_inference_sprt_proto_rawDescOnce sync.Once
	file_inference_inference_sprt_proto_rawDescData = file_inference_inference_sprt_proto_rawDesc
)

func file_inference_inference_sprt_proto_rawDescGZIP() []byte {
	file_inference_inference_sprt_proto_rawDescOnce.Do(func() {
		file_inference_inference_sprt_proto_rawDescData = protoimpl.X.CompressGZIP(file_inference_inference_sprt_proto_rawDescData)
	})
	return file_inference_inference_sprt_proto_rawDescData
}

var file_inference_inference_sprt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inference_inference_sprt_proto_goTypes = []interface{}{
	(*SPRTPrecomputedValues)(nil), // 0: inference.inference.SPRTPrecomputedValues
	(*Decimal)(nil),               // 1: inference.inference.Decimal
}
var file_inference_inference_sprt_proto_depIdxs = []int32{
	1, // 0: inference.inference.SPRTPrecomputedValues.invalidation_log_fail:type_name -> inference.inference.Decimal
	1, // 1: inference.inference.SPRTPrecomputedValues.invalidation_log_pass:type_name -> inference.inference.Decimal
	1, // 2: inference.inference.SPRTPrecomputedValues.inactive_log_fail:type_name -> inference.inference.Decimal
	1, // 3: inference.inference.SPRTPrecomputedValues.inactive_log_pass:type_name -> inference.inference.Decimal
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inference_inference_sprt_proto_init() }
func file_inference_inference_sprt_proto_init() {
	if File_inference_inference_sprt_proto != nil {
		return
	}
	file_inference_inference_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_inference_inference_sprt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPRTPrecomputedValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inference_inference_sprt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inference_inference_sprt_proto_goTypes,
		DependencyIndexes: file_inference_inference_sprt_proto_depIdxs,
		MessageInfos:      file_inference_inference_sprt_proto_msgTypes,
	}.Build()
	File_inference_inference_sprt_proto = out.File
	file_inference_inference_sprt_proto_rawDesc = nil
	file_inference_inference_sprt_proto_goTypes = nil
	file_inference_inference_sprt_proto_depIdxs = nil
}
