package transport

import (
	"github.com/labstack/echo/v4"
)

// X-Devshard-Error classifies non-OK host responses for observability and
// direct host API clients. The gateway treats all upstream 503s uniformly
// (hide-redirect via redundancy and throttling), except an undeclared-version
// catalog miss, which is forwarded as 503 with this header.
const HeaderDevshardError = "X-Devshard-Error"

// X-Devshard-Router-Error is reserved for catalog misses generated by
// versiond-router itself. Hosts use X-Devshard-Error for their own codes;
// they must not be able to set this header (the router will strip it from
// backend responses when the limiter exemption is gated on it).
const HeaderDevshardRouterError = "X-Devshard-Router-Error"

const (
	DevshardErrorRequestsDisabled     = "requests_disabled"
	DevshardErrorInitializing         = "initializing"
	DevshardErrorNotImplemented       = "not_implemented"
	DevshardErrorChainUnavailable     = "chain_unavailable"
	DevshardErrorEscrowSettled        = "escrow_settled"
	DevshardErrorUndeclaredVersion    = "undeclared_version"
	DevshardErrorHeightSeedIncomplete = "height_seed_incomplete"
	DevshardErrorCatalogPending       = "catalog_pending"
)

// HTTPError returns an echo HTTP error and sets X-Devshard-Error when devshardCode is non-empty.
func HTTPError(c echo.Context, code int, devshardCode, message string) error {
	if devshardCode != "" {
		c.Response().Header().Set(HeaderDevshardError, devshardCode)
	}
	return echo.NewHTTPError(code, message)
}
