// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/activeparticipants.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Wrapper message to enable double repeated structure for model-based MLNode organization
type ModelMLNodes struct {
	MlNodes []*MLNodeInfo `protobuf:"bytes,1,rep,name=ml_nodes,json=mlNodes,proto3" json:"ml_nodes,omitempty"`
}

func (m *ModelMLNodes) Reset()         { *m = ModelMLNodes{} }
func (m *ModelMLNodes) String() string { return proto.CompactTextString(m) }
func (*ModelMLNodes) ProtoMessage()    {}
func (*ModelMLNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd4d0434f36692fa, []int{0}
}
func (m *ModelMLNodes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModelMLNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModelMLNodes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ModelMLNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelMLNodes.Merge(m, src)
}
func (m *ModelMLNodes) XXX_Size() int {
	return m.Size()
}
func (m *ModelMLNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelMLNodes.DiscardUnknown(m)
}

var xxx_messageInfo_ModelMLNodes proto.InternalMessageInfo

func (m *ModelMLNodes) GetMlNodes() []*MLNodeInfo {
	if m != nil {
		return m.MlNodes
	}
	return nil
}

// Not added to the Genesis, because at genesis it's constructed based on Participants
type ActiveParticipants struct {
	Participants         []*ActiveParticipant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	EpochGroupId         uint64               `protobuf:"varint,2,opt,name=epoch_group_id,json=epochGroupId,proto3" json:"epoch_group_id,omitempty"`
	PocStartBlockHeight  int64                `protobuf:"varint,3,opt,name=poc_start_block_height,json=pocStartBlockHeight,proto3" json:"poc_start_block_height,omitempty"`
	EffectiveBlockHeight int64                `protobuf:"varint,4,opt,name=effective_block_height,json=effectiveBlockHeight,proto3" json:"effective_block_height,omitempty"`
	CreatedAtBlockHeight int64                `protobuf:"varint,5,opt,name=created_at_block_height,json=createdAtBlockHeight,proto3" json:"created_at_block_height,omitempty"`
	EpochId              uint64               `protobuf:"varint,6,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	// cap_weight_applied is true when applyPreviousConfirmedWeightCap ran for this
	// epoch, including the legitimate all-zero case (every participant is new or
	// was removed last epoch). False means a pre-upgrade epoch whose CapWeight
	// field was never populated, so consumers may fall back to Weight.
	CapWeightApplied bool `protobuf:"varint,7,opt,name=cap_weight_applied,json=capWeightApplied,proto3" json:"cap_weight_applied,omitempty"`
}

func (m *ActiveParticipants) Reset()         { *m = ActiveParticipants{} }
func (m *ActiveParticipants) String() string { return proto.CompactTextString(m) }
func (*ActiveParticipants) ProtoMessage()    {}
func (*ActiveParticipants) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd4d0434f36692fa, []int{1}
}
func (m *ActiveParticipants) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveParticipants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveParticipants.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveParticipants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveParticipants.Merge(m, src)
}
func (m *ActiveParticipants) XXX_Size() int {
	return m.Size()
}
func (m *ActiveParticipants) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveParticipants.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveParticipants proto.InternalMessageInfo

func (m *ActiveParticipants) GetParticipants() []*ActiveParticipant {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *ActiveParticipants) GetEpochGroupId() uint64 {
	if m != nil {
		return m.EpochGroupId
	}
	return 0
}

func (m *ActiveParticipants) GetPocStartBlockHeight() int64 {
	if m != nil {
		return m.PocStartBlockHeight
	}
	return 0
}

func (m *ActiveParticipants) GetEffectiveBlockHeight() int64 {
	if m != nil {
		return m.EffectiveBlockHeight
	}
	return 0
}

func (m *ActiveParticipants) GetCreatedAtBlockHeight() int64 {
	if m != nil {
		return m.CreatedAtBlockHeight
	}
	return 0
}

func (m *ActiveParticipants) GetEpochId() uint64 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *ActiveParticipants) GetCapWeightApplied() bool {
	if m != nil {
		return m.CapWeightApplied
	}
	return false
}

type ActiveParticipant struct {
	Index        string              `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ValidatorKey string              `protobuf:"bytes,2,opt,name=validator_key,json=validatorKey,proto3" json:"validator_key,omitempty"`
	Weight       int64               `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	InferenceUrl string              `protobuf:"bytes,4,opt,name=inference_url,json=inferenceUrl,proto3" json:"inference_url,omitempty"`
	Models       []string            `protobuf:"bytes,5,rep,name=models,proto3" json:"models,omitempty"`
	Seed         *RandomSeed         `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`
	MlNodes      []*ModelMLNodes     `protobuf:"bytes,7,rep,name=ml_nodes,json=mlNodes,proto3" json:"ml_nodes,omitempty"`
	VotingPowers []*ModelVotingPower `protobuf:"bytes,8,rep,name=voting_powers,json=votingPowers,proto3" json:"voting_powers,omitempty"`
	// cap_weight is the trust weight used for governance voting, BLS threshold
	// signing and cPoC validation voting power. It is capped at the confirmed
	// weight the participant held in the previous epoch (0 for participants that
	// were absent last epoch), while weight (field 3) remains the real weight used
	// for rewards, cPoC confirmation and the next-epoch cap baseline.
	CapWeight int64 `protobuf:"varint,9,opt,name=cap_weight,json=capWeight,proto3" json:"cap_weight,omitempty"`
}

func (m *ActiveParticipant) Reset()         { *m = ActiveParticipant{} }
func (m *ActiveParticipant) String() string { return proto.CompactTextString(m) }
func (*ActiveParticipant) ProtoMessage()    {}
func (*ActiveParticipant) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd4d0434f36692fa, []int{2}
}
func (m *ActiveParticipant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveParticipant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveParticipant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveParticipant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveParticipant.Merge(m, src)
}
func (m *ActiveParticipant) XXX_Size() int {
	return m.Size()
}
func (m *ActiveParticipant) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveParticipant.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveParticipant proto.InternalMessageInfo

func (m *ActiveParticipant) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ActiveParticipant) GetValidatorKey() string {
	if m != nil {
		return m.ValidatorKey
	}
	return ""
}

func (m *ActiveParticipant) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ActiveParticipant) GetInferenceUrl() string {
	if m != nil {
		return m.InferenceUrl
	}
	return ""
}

func (m *ActiveParticipant) GetModels() []string {
	if m != nil {
		return m.Models
	}
	return nil
}

func (m *ActiveParticipant) GetSeed() *RandomSeed {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *ActiveParticipant) GetMlNodes() []*ModelMLNodes {
	if m != nil {
		return m.MlNodes
	}
	return nil
}

func (m *ActiveParticipant) GetVotingPowers() []*ModelVotingPower {
	if m != nil {
		return m.VotingPowers
	}
	return nil
}

func (m *ActiveParticipant) GetCapWeight() int64 {
	if m != nil {
		return m.CapWeight
	}
	return 0
}

func init() {
	proto.RegisterType((*ModelMLNodes)(nil), "inference.inference.ModelMLNodes")
	proto.RegisterType((*ActiveParticipants)(nil), "inference.inference.ActiveParticipants")
	proto.RegisterType((*ActiveParticipant)(nil), "inference.inference.ActiveParticipant")
}

func init() {
	proto.RegisterFile("inference/inference/activeparticipants.proto", fileDescriptor_cd4d0434f36692fa)
}

var fileDescriptor_cd4d0434f36692fa = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x4f, 0x14, 0x31,
	0x18, 0x66, 0x58, 0x60, 0x77, 0xea, 0x60, 0xb4, 0x10, 0x1c, 0x49, 0x1c, 0x47, 0x14, 0x33, 0x31,
	0x64, 0x49, 0x44, 0x2e, 0xc6, 0x0b, 0x5c, 0x14, 0x14, 0x25, 0x25, 0x6a, 0xe2, 0xa5, 0x29, 0xed,
	0xbb, 0xbb, 0x0d, 0xb3, 0xd3, 0xa6, 0xd3, 0x5d, 0xe0, 0xe8, 0x3f, 0xf0, 0x67, 0x79, 0xe4, 0xe8,
	0xd1, 0xc0, 0x2f, 0xf0, 0x1f, 0x98, 0xe9, 0x6c, 0x86, 0x59, 0x18, 0x6e, 0xef, 0xc7, 0xf3, 0xbc,
	0xed, 0xf3, 0xf6, 0x29, 0xda, 0x90, 0x59, 0x0f, 0x0c, 0x64, 0x1c, 0x36, 0xaf, 0x23, 0xc6, 0xad,
	0x1c, 0x83, 0x66, 0xc6, 0x4a, 0x2e, 0x35, 0xcb, 0x6c, 0xde, 0xd5, 0x46, 0x59, 0x85, 0x97, 0x2a,
	0x4c, 0xb7, 0x8a, 0x56, 0xd7, 0x9b, 0x46, 0x18, 0x96, 0x09, 0x35, 0xa4, 0x39, 0x80, 0x28, 0xb9,
	0xab, 0xaf, 0x9a, 0x60, 0xa0, 0x15, 0x1f, 0xd0, 0xbe, 0x51, 0x23, 0x4d, 0x05, 0xb3, 0x6c, 0x82,
	0x4d, 0x9a, 0xb0, 0x5a, 0x71, 0x2a, 0x20, 0x85, 0x3e, 0xb3, 0x52, 0x65, 0x25, 0x72, 0x6d, 0x1f,
	0x05, 0x07, 0x4a, 0x40, 0x7a, 0xf0, 0xe9, 0xb3, 0x12, 0x90, 0xe3, 0xb7, 0xa8, 0x33, 0x4c, 0x69,
	0x56, 0xc4, 0xa1, 0x17, 0xb7, 0x92, 0x7b, 0xaf, 0x9f, 0x76, 0x1b, 0x2e, 0xdd, 0x2d, 0xf1, 0x7b,
	0x59, 0x4f, 0x91, 0xf6, 0x30, 0x75, 0xdc, 0xb5, 0x7f, 0xb3, 0x08, 0xef, 0x38, 0xe9, 0x87, 0x35,
	0xe9, 0x78, 0x1f, 0x05, 0xf5, 0x55, 0x4c, 0xc6, 0xbe, 0x6c, 0x1c, 0x7b, 0x8b, 0x4e, 0xa6, 0xb8,
	0xf8, 0x05, 0xba, 0x5f, 0x97, 0x2c, 0x45, 0x38, 0x1b, 0x7b, 0xc9, 0x1c, 0x09, 0x5c, 0xf5, 0x7d,
	0x51, 0xdc, 0x13, 0x78, 0x0b, 0xad, 0x14, 0x62, 0x73, 0xcb, 0x8c, 0xa5, 0xc7, 0xa9, 0xe2, 0x27,
	0x74, 0x00, 0xb2, 0x3f, 0xb0, 0x61, 0x2b, 0xf6, 0x92, 0x16, 0x59, 0xd2, 0x8a, 0x1f, 0x15, 0xcd,
	0xdd, 0xa2, 0xf7, 0xc1, 0xb5, 0xf0, 0x1b, 0xb4, 0x02, 0xbd, 0x1e, 0xb8, 0x0b, 0x4c, 0x93, 0xe6,
	0x1c, 0x69, 0xb9, 0xea, 0xd6, 0x59, 0xdb, 0xe8, 0x11, 0x37, 0xc0, 0x2c, 0x08, 0xca, 0x6e, 0x9c,
	0x35, 0x5f, 0xd2, 0x26, 0xed, 0x9d, 0xa9, 0xc3, 0x1e, 0xa3, 0x4e, 0xa9, 0x43, 0x8a, 0x70, 0xc1,
	0x29, 0x68, 0xbb, 0x7c, 0x4f, 0xe0, 0x0d, 0x84, 0x39, 0xd3, 0xf4, 0xd4, 0x01, 0x29, 0xd3, 0x3a,
	0x95, 0x20, 0xc2, 0x76, 0xec, 0x25, 0x1d, 0xf2, 0x80, 0x33, 0xfd, 0xdd, 0x35, 0x76, 0xca, 0xfa,
	0xda, 0xcf, 0x16, 0x7a, 0x78, 0x6b, 0x69, 0x78, 0x19, 0xcd, 0xcb, 0x4c, 0xc0, 0x59, 0xe8, 0xc5,
	0x5e, 0xe2, 0x93, 0x32, 0xc1, 0xcf, 0xd1, 0xe2, 0x98, 0xa5, 0x52, 0x30, 0xab, 0x0c, 0x3d, 0x81,
	0x73, 0xb7, 0x3b, 0x9f, 0x04, 0x55, 0xf1, 0x23, 0x9c, 0xe3, 0x15, 0xb4, 0x70, 0x5a, 0xdf, 0xd5,
	0x24, 0x2b, 0xc8, 0xd5, 0x33, 0xd1, 0x91, 0x49, 0xdd, 0x56, 0x7c, 0x12, 0x54, 0xc5, 0xaf, 0x26,
	0x2d, 0xc8, 0xc3, 0xc2, 0x4d, 0x79, 0x38, 0x1f, 0xb7, 0x12, 0x9f, 0x4c, 0x32, 0xbc, 0x85, 0xe6,
	0x0a, 0x27, 0x3b, 0xa9, 0x77, 0x39, 0x8a, 0x38, 0xc7, 0x1f, 0x01, 0x08, 0xe2, 0xc0, 0xf8, 0x5d,
	0xcd, 0x8a, 0x6d, 0xe7, 0x99, 0x67, 0xcd, 0x56, 0xac, 0xf9, 0xb7, 0x32, 0x23, 0xde, 0x47, 0x8b,
	0x63, 0x65, 0x65, 0xd6, 0xa7, 0x5a, 0x9d, 0x82, 0xc9, 0xc3, 0x8e, 0x1b, 0xb1, 0x7e, 0xf7, 0x88,
	0x6f, 0x0e, 0x7e, 0x58, 0xa0, 0x49, 0x30, 0xbe, 0x4e, 0x72, 0xfc, 0x04, 0xa1, 0xeb, 0x27, 0x09,
	0x7d, 0xb7, 0x17, 0xbf, 0x7a, 0x8a, 0xdd, 0x2f, 0xbf, 0x2f, 0x23, 0xef, 0xe2, 0x32, 0xf2, 0xfe,
	0x5e, 0x46, 0xde, 0xaf, 0xab, 0x68, 0xe6, 0xe2, 0x2a, 0x9a, 0xf9, 0x73, 0x15, 0xcd, 0xfc, 0xd8,
	0xee, 0x4b, 0x3b, 0x18, 0x1d, 0x77, 0xb9, 0x1a, 0x6e, 0x6a, 0xa3, 0xc4, 0x88, 0xdb, 0x9c, 0xcb,
	0x1b, 0xff, 0xf2, 0xac, 0x16, 0xdb, 0x73, 0x0d, 0xf9, 0xf1, 0x82, 0xfb, 0x9b, 0x5b, 0xff, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xd9, 0x0c, 0x93, 0xfb, 0x5d, 0x04, 0x00, 0x00,
}

func (m *ModelMLNodes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModelMLNodes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ModelMLNodes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MlNodes) > 0 {
		for iNdEx := len(m.MlNodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MlNodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintActiveparticipants(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ActiveParticipants) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveParticipants) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveParticipants) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CapWeightApplied {
		i--
		if m.CapWeightApplied {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.EpochId != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.EpochId))
		i--
		dAtA[i] = 0x30
	}
	if m.CreatedAtBlockHeight != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.CreatedAtBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.EffectiveBlockHeight != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.EffectiveBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.PocStartBlockHeight != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.PocStartBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochGroupId != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.EpochGroupId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Participants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintActiveparticipants(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ActiveParticipant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveParticipant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveParticipant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CapWeight != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.CapWeight))
		i--
		dAtA[i] = 0x48
	}
	if len(m.VotingPowers) > 0 {
		for iNdEx := len(m.VotingPowers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VotingPowers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintActiveparticipants(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.MlNodes) > 0 {
		for iNdEx := len(m.MlNodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MlNodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintActiveparticipants(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.Seed != nil {
		{
			size, err := m.Seed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintActiveparticipants(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.Models) > 0 {
		for iNdEx := len(m.Models) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Models[iNdEx])
			copy(dAtA[i:], m.Models[iNdEx])
			i = encodeVarintActiveparticipants(dAtA, i, uint64(len(m.Models[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.InferenceUrl) > 0 {
		i -= len(m.InferenceUrl)
		copy(dAtA[i:], m.InferenceUrl)
		i = encodeVarintActiveparticipants(dAtA, i, uint64(len(m.InferenceUrl)))
		i--
		dAtA[i] = 0x22
	}
	if m.Weight != 0 {
		i = encodeVarintActiveparticipants(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorKey) > 0 {
		i -= len(m.ValidatorKey)
		copy(dAtA[i:], m.ValidatorKey)
		i = encodeVarintActiveparticipants(dAtA, i, uint64(len(m.ValidatorKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintActiveparticipants(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintActiveparticipants(dAtA []byte, offset int, v uint64) int {
	offset -= sovActiveparticipants(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ModelMLNodes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MlNodes) > 0 {
		for _, e := range m.MlNodes {
			l = e.Size()
			n += 1 + l + sovActiveparticipants(uint64(l))
		}
	}
	return n
}

func (m *ActiveParticipants) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for _, e := range m.Participants {
			l = e.Size()
			n += 1 + l + sovActiveparticipants(uint64(l))
		}
	}
	if m.EpochGroupId != 0 {
		n += 1 + sovActiveparticipants(uint64(m.EpochGroupId))
	}
	if m.PocStartBlockHeight != 0 {
		n += 1 + sovActiveparticipants(uint64(m.PocStartBlockHeight))
	}
	if m.EffectiveBlockHeight != 0 {
		n += 1 + sovActiveparticipants(uint64(m.EffectiveBlockHeight))
	}
	if m.CreatedAtBlockHeight != 0 {
		n += 1 + sovActiveparticipants(uint64(m.CreatedAtBlockHeight))
	}
	if m.EpochId != 0 {
		n += 1 + sovActiveparticipants(uint64(m.EpochId))
	}
	if m.CapWeightApplied {
		n += 2
	}
	return n
}

func (m *ActiveParticipant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovActiveparticipants(uint64(l))
	}
	l = len(m.ValidatorKey)
	if l > 0 {
		n += 1 + l + sovActiveparticipants(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovActiveparticipants(uint64(m.Weight))
	}
	l = len(m.InferenceUrl)
	if l > 0 {
		n += 1 + l + sovActiveparticipants(uint64(l))
	}
	if len(m.Models) > 0 {
		for _, s := range m.Models {
			l = len(s)
			n += 1 + l + sovActiveparticipants(uint64(l))
		}
	}
	if m.Seed != nil {
		l = m.Seed.Size()
		n += 1 + l + sovActiveparticipants(uint64(l))
	}
	if len(m.MlNodes) > 0 {
		for _, e := range m.MlNodes {
			l = e.Size()
			n += 1 + l + sovActiveparticipants(uint64(l))
		}
	}
	if len(m.VotingPowers) > 0 {
		for _, e := range m.VotingPowers {
			l = e.Size()
			n += 1 + l + sovActiveparticipants(uint64(l))
		}
	}
	if m.CapWeight != 0 {
		n += 1 + sovActiveparticipants(uint64(m.CapWeight))
	}
	return n
}

func sovActiveparticipants(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActiveparticipants(x uint64) (n int) {
	return sovActiveparticipants(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ModelMLNodes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActiveparticipants
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModelMLNodes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModelMLNodes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MlNodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MlNodes = append(m.MlNodes, &MLNodeInfo{})
			if err := m.MlNodes[len(m.MlNodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActiveparticipants(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveParticipants) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActiveparticipants
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveParticipants: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveParticipants: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, &ActiveParticipant{})
			if err := m.Participants[len(m.Participants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochGroupId", wireType)
			}
			m.EpochGroupId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochGroupId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PocStartBlockHeight", wireType)
			}
			m.PocStartBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PocStartBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveBlockHeight", wireType)
			}
			m.EffectiveBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtBlockHeight", wireType)
			}
			m.CreatedAtBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochId", wireType)
			}
			m.EpochId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapWeightApplied", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CapWeightApplied = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipActiveparticipants(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveParticipant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActiveparticipants
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveParticipant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveParticipant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InferenceUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InferenceUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Models", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Models = append(m.Models, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Seed == nil {
				m.Seed = &RandomSeed{}
			}
			if err := m.Seed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MlNodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MlNodes = append(m.MlNodes, &ModelMLNodes{})
			if err := m.MlNodes[len(m.MlNodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPowers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VotingPowers = append(m.VotingPowers, &ModelVotingPower{})
			if err := m.VotingPowers[len(m.VotingPowers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapWeight", wireType)
			}
			m.CapWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CapWeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActiveparticipants(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActiveparticipants
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActiveparticipants(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActiveparticipants
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActiveparticipants
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActiveparticipants
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActiveparticipants
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActiveparticipants
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActiveparticipants        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActiveparticipants          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActiveparticipants = fmt.Errorf("proto: unexpected end of group")
)
