package types

// DONTCOVER

import (
	sdkerrors "cosmossdk.io/errors"
)

// x/inference module sentinel errors
var (
	ErrInvalidSigner                         = sdkerrors.Register(ModuleName, 1100, "expected gov account as only signer for proposal message")
	ErrInferenceIdExists                     = sdkerrors.Register(ModuleName, 1101, "inference with id already exists")
	ErrInferenceNotFound                     = sdkerrors.Register(ModuleName, 1102, "inference with id not found")
	ErrParticipantNotFound                   = sdkerrors.Register(ModuleName, 1103, "participant not found")
	ErrInferenceNotFinished                  = sdkerrors.Register(ModuleName, 1104, "inference not finished")
	ErrParticipantCannotValidateOwnInference = sdkerrors.Register(ModuleName, 1105, "participant cannot validate own inference")
	ErrRequesterCannotPay                    = sdkerrors.Register(ModuleName, 1106, "requester cannot pay for inference")
	ErrPocWrongStartBlockHeight              = sdkerrors.Register(ModuleName, 1107, "start block height must be divisible by 240")
	ErrPocTooLate                            = sdkerrors.Register(ModuleName, 1108, "POC submission is too late")
	ErrAccountAlreadyExists                  = sdkerrors.Register(ModuleName, 1110, "account already exists")
	ErrCurrentEpochGroupNotFound             = sdkerrors.Register(ModuleName, 1112, "current epoch group not found")
	ErrPocAddressInvalid                     = sdkerrors.Register(ModuleName, 1113, "POC address marked invalid, no longer allowed")
	ErrNegativeCoinBalance                   = sdkerrors.Register(ModuleName, 1114, "negative coin balance")
	ErrClaimSignatureInvalid                 = sdkerrors.Register(ModuleName, 1116, "claim signature invalid")
	ErrValidationsMissed                     = sdkerrors.Register(ModuleName, 1117, "validations missed")
	ErrCannotMintNegativeCoins               = sdkerrors.Register(ModuleName, 1119, "cannot mint negative coins")
	ErrCannotCreateSubGroupFromSubGroup      = sdkerrors.Register(ModuleName, 1123, "cannot create a sub-group from a sub-group")
	ErrCannotGetSubGroupFromSubGroup         = sdkerrors.Register(ModuleName, 1124, "cannot get a sub-group from a sub-group")
	ErrInferenceHasInvalidModel              = sdkerrors.Register(ModuleName, 1125, "inference has a model that has no sub-group")
	ErrEpochGroupDataNotFound                = sdkerrors.Register(ModuleName, 1126, "epoch group data not found for the given poc start block height and model id")
	ErrEffectiveEpochNotFound                = sdkerrors.Register(ModuleName, 1127, "current epoch not found")
	ErrUpcomingEpochNotFound                 = sdkerrors.Register(ModuleName, 1128, "upcoming epoch group not found")
	ErrPreviousEpochNotFound                 = sdkerrors.Register(ModuleName, 1129, "previous epoch group not found")
	ErrLatestEpochNotFound                   = sdkerrors.Register(ModuleName, 1130, "latest epoch group data not found")
	ErrEpochGroupDataAlreadyExists           = sdkerrors.Register(ModuleName, 1131, "epoch group data already exists for the given poc start block height and model id")
	ErrInvalidSignature                      = sdkerrors.Register(ModuleName, 1132, "invalid keys provided for StartInference")
	ErrInferenceExpired                      = sdkerrors.Register(ModuleName, 1133, "inference has expired")
	ErrInvalidModel                          = sdkerrors.Register(ModuleName, 1134, "invalid model")
	ErrModelSnapshotNotFound                 = sdkerrors.Register(ModuleName, 1135, "model snapshot not found in epoch group data")
	ErrEpochNotFound                         = sdkerrors.Register(ModuleName, 1136, "epoch not found")
	ErrIllegalState                          = sdkerrors.Register(ModuleName, 1137, "illegal state for the operation requested")
	ErrInvalidValidationThreshold            = sdkerrors.Register(ModuleName, 1138, "validation threshold must be in [0, 100] range")
	ErrDuplicateNodeId                       = sdkerrors.Register(ModuleName, 1140, "duplicate node id")
	ErrNegativeRewardAmount                  = sdkerrors.Register(ModuleName, 1142, "negative reward amount")
	ErrDuplicateValidation                   = sdkerrors.Register(ModuleName, 1143, "participant has already validated this inference")
	ErrPubKeyUnavailable                     = sdkerrors.Register(ModuleName, 1144, "account has no public key")
	ErrPocNodeIdEmpty                        = sdkerrors.Register(ModuleName, 1145, "node id is empty")
	ErrInferenceFinishProcessed              = sdkerrors.Register(ModuleName, 1146, "inference has already finished processed")
	ErrInferenceStartProcessed               = sdkerrors.Register(ModuleName, 1147, "inference has already started processed")
	ErrUnknownAllowList                      = sdkerrors.Register(ModuleName, 1148, "unknown allow list")
	ErrPubKeyDoesNotMatchAddress             = sdkerrors.Register(ModuleName, 1149, "public key does not match address")
	ErrSignatureTooOld                       = sdkerrors.Register(ModuleName, 1150, "signature is too old")
	ErrSignatureInFuture                     = sdkerrors.Register(ModuleName, 1151, "signature is in the future")
	ErrValidationPayloadDeprecated           = sdkerrors.Register(ModuleName, 1152, "validation response payload is deprecated")
	ErrBridgeAddressNotFound                 = sdkerrors.Register(ModuleName, 1153, "bridge addresses not found")
	ErrDeveloperNotAllowlisted               = sdkerrors.Register(ModuleName, 1154, "developer is not allowlisted to request inference at this height")
	ErrParticipantBlocked                    = sdkerrors.Register(ModuleName, 1155, "participant is blocked from participating in PoC")
	ErrNewParticipantRegistrationClosed      = sdkerrors.Register(ModuleName, 1156, "new participant registration is closed")
	ErrArithmeticOverflow                    = sdkerrors.Register(ModuleName, 1157, "arithmetic overflow")
	ErrInvalidEscrowAmount                   = sdkerrors.Register(ModuleName, 1158, "invalid escrow amount")
	ErrTokenCountOutOfRange                  = sdkerrors.Register(ModuleName, 1159, "token count out of range")
	ErrPocValidationAlreadyExists            = sdkerrors.Register(ModuleName, 1160, "PoC validation already exists for this participant from this validator")
	ErrDeprecated                            = sdkerrors.Register(ModuleName, 1161, "this message type is deprecated")
	ErrPocArtifactVectorEmpty                = sdkerrors.Register(ModuleName, 1162, "artifact vector is empty")
	ErrNotSupported                          = sdkerrors.Register(ModuleName, 1163, "operation not supported in current mode")
	ErrInvalidAddress                        = sdkerrors.Register(ModuleName, 1164, "invalid address")
	ErrTransferAgentNotAllowlisted           = sdkerrors.Register(ModuleName, 1165, "transfer agent not in allowlist")
	ErrInvalidPermission                     = sdkerrors.Register(ModuleName, 1166, "invalid permission")
	ErrAccountNotFound                       = sdkerrors.Register(ModuleName, 1167, "account not found")
	ErrNotAContractAddress                   = sdkerrors.Register(ModuleName, 1168, "address is not a contract address")
	ErrActiveParticipantNotFound             = sdkerrors.Register(ModuleName, 1169, "participant is not active")
	ErrDevComponentMismatch                  = sdkerrors.Register(ModuleName, 1170, "developer signature components mismatch")
	ErrTAComponentMismatch                   = sdkerrors.Register(ModuleName, 1171, "transfer agent signature components mismatch")
	ErrInferenceRoleMismatch                 = sdkerrors.Register(ModuleName, 1172, "inference role/address invariant mismatch")
	ErrNotAllowedEscrowCreator               = sdkerrors.Register(ModuleName, 1173, "address is not allowed to create devshard escrows for devshards")
	ErrEpochIndexOutOfRange                  = sdkerrors.Register(ModuleName, 1174, "epoch index can only be current or upcoming epoch")
	ErrSelfDelegation                        = sdkerrors.Register(ModuleName, 1175, "self-delegation not allowed")
	ErrInvalidDelegateTarget                 = sdkerrors.Register(ModuleName, 1176, "invalid delegation target")
	ErrMaintenanceNotImplemented             = sdkerrors.Register(ModuleName, 1177, "maintenance feature not yet implemented")
	ErrMaintenanceDisabled                   = sdkerrors.Register(ModuleName, 1178, "maintenance windows are disabled")
	ErrMaintenanceInsufficientCredit         = sdkerrors.Register(ModuleName, 1179, "insufficient maintenance credit")
	ErrMaintenanceInsufficientLeadTime       = sdkerrors.Register(ModuleName, 1180, "start height does not satisfy minimum scheduling lead time")
	ErrMaintenanceDurationExceeded           = sdkerrors.Register(ModuleName, 1181, "duration exceeds maximum maintenance window blocks")
	ErrMaintenanceConcurrentCountExceeded    = sdkerrors.Register(ModuleName, 1182, "concurrent maintenance participant count cap exceeded")
	ErrMaintenanceConcurrentPowerExceeded    = sdkerrors.Register(ModuleName, 1183, "concurrent maintenance power cap exceeded")
	ErrMaintenanceOverlap                    = sdkerrors.Register(ModuleName, 1184, "maintenance window overlaps existing reservation for this participant")
	ErrMaintenanceAlreadyScheduled           = sdkerrors.Register(ModuleName, 1185, "participant already has a scheduled maintenance window")
	ErrMaintenanceReservationNotFound        = sdkerrors.Register(ModuleName, 1186, "maintenance reservation not found")
	ErrMaintenanceNotScheduled               = sdkerrors.Register(ModuleName, 1187, "reservation is not in scheduled state")
	ErrMaintenanceOverlapsPoCPhase           = sdkerrors.Register(ModuleName, 1188, "maintenance window overlaps PoC commit/exchange phase")
	ErrMaintenanceOverlapsDKGPhase           = sdkerrors.Register(ModuleName, 1189, "maintenance window overlaps DKG phase")
	ErrMaintenanceInvalidParticipant         = sdkerrors.Register(ModuleName, 1190, "invalid participant address")
	ErrMaintenanceZeroDuration               = sdkerrors.Register(ModuleName, 1191, "duration_blocks must be positive")
	ErrMaintenanceCompletionHeightOverflow   = sdkerrors.Register(ModuleName, 1192, "maintenance completion height overflows int64")
	ErrBridgeValidatorNotInTxEpochGroup      = sdkerrors.Register(ModuleName, 1193, "validator not in transaction's epoch group")
	ErrBridgeAlreadyValidated                = sdkerrors.Register(ModuleName, 1194, "validator has already validated this transaction")
	ErrBridgeValidatorNotInActiveGroup       = sdkerrors.Register(ModuleName, 1195, "validator not in active participants")
	ErrBridgeContentMismatch                 = sdkerrors.Register(ModuleName, 1196, "validator posted a transaction with content mismatch")
	ErrInvalidDecimalExponent                = sdkerrors.Register(ModuleName, 1197, "decimal exponent must be between -18 and 18")
)
