// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/maintenance.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MaintenanceReservationStatus represents the lifecycle status of a maintenance reservation.
type MaintenanceReservationStatus int32

const (
	MaintenanceReservationStatus_MAINTENANCE_RESERVATION_STATUS_UNSPECIFIED MaintenanceReservationStatus = 0
	MaintenanceReservationStatus_MAINTENANCE_RESERVATION_STATUS_SCHEDULED   MaintenanceReservationStatus = 1
	MaintenanceReservationStatus_MAINTENANCE_RESERVATION_STATUS_ACTIVE      MaintenanceReservationStatus = 2
	MaintenanceReservationStatus_MAINTENANCE_RESERVATION_STATUS_COMPLETED   MaintenanceReservationStatus = 3
	MaintenanceReservationStatus_MAINTENANCE_RESERVATION_STATUS_CANCELED    MaintenanceReservationStatus = 4
)

var MaintenanceReservationStatus_name = map[int32]string{
	0: "MAINTENANCE_RESERVATION_STATUS_UNSPECIFIED",
	1: "MAINTENANCE_RESERVATION_STATUS_SCHEDULED",
	2: "MAINTENANCE_RESERVATION_STATUS_ACTIVE",
	3: "MAINTENANCE_RESERVATION_STATUS_COMPLETED",
	4: "MAINTENANCE_RESERVATION_STATUS_CANCELED",
}

var MaintenanceReservationStatus_value = map[string]int32{
	"MAINTENANCE_RESERVATION_STATUS_UNSPECIFIED": 0,
	"MAINTENANCE_RESERVATION_STATUS_SCHEDULED":   1,
	"MAINTENANCE_RESERVATION_STATUS_ACTIVE":      2,
	"MAINTENANCE_RESERVATION_STATUS_COMPLETED":   3,
	"MAINTENANCE_RESERVATION_STATUS_CANCELED":    4,
}

func (x MaintenanceReservationStatus) String() string {
	return proto.EnumName(MaintenanceReservationStatus_name, int32(x))
}

func (MaintenanceReservationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e2613976197972a, []int{0}
}

// MaintenanceTransitionType represents the type of lifecycle transition at a given block height.
type MaintenanceTransitionType int32

const (
	MaintenanceTransitionType_MAINTENANCE_TRANSITION_TYPE_UNSPECIFIED MaintenanceTransitionType = 0
	MaintenanceTransitionType_MAINTENANCE_TRANSITION_TYPE_ACTIVATE    MaintenanceTransitionType = 1
	MaintenanceTransitionType_MAINTENANCE_TRANSITION_TYPE_COMPLETE    MaintenanceTransitionType = 2
)

var MaintenanceTransitionType_name = map[int32]string{
	0: "MAINTENANCE_TRANSITION_TYPE_UNSPECIFIED",
	1: "MAINTENANCE_TRANSITION_TYPE_ACTIVATE",
	2: "MAINTENANCE_TRANSITION_TYPE_COMPLETE",
}

var MaintenanceTransitionType_value = map[string]int32{
	"MAINTENANCE_TRANSITION_TYPE_UNSPECIFIED": 0,
	"MAINTENANCE_TRANSITION_TYPE_ACTIVATE":    1,
	"MAINTENANCE_TRANSITION_TYPE_COMPLETE":    2,
}

func (x MaintenanceTransitionType) String() string {
	return proto.EnumName(MaintenanceTransitionType_name, int32(x))
}

func (MaintenanceTransitionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e2613976197972a, []int{1}
}

// MaintenanceReservation represents a scheduled maintenance window for a participant.
type MaintenanceReservation struct {
	ReservationId     uint64                       `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Participant       string                       `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`
	StartHeight       int64                        `protobuf:"varint,3,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	DurationBlocks    uint64                       `protobuf:"varint,4,opt,name=duration_blocks,json=durationBlocks,proto3" json:"duration_blocks,omitempty"`
	CreatedBy         string                       `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Status            MaintenanceReservationStatus `protobuf:"varint,6,opt,name=status,proto3,enum=inference.inference.MaintenanceReservationStatus" json:"status,omitempty"`
	ActivationWarning string                       `protobuf:"bytes,7,opt,name=activation_warning,json=activationWarning,proto3" json:"activation_warning,omitempty"`
}

func (m *MaintenanceReservation) Reset()         { *m = MaintenanceReservation{} }
func (m *MaintenanceReservation) String() string { return proto.CompactTextString(m) }
func (*MaintenanceReservation) ProtoMessage()    {}
func (*MaintenanceReservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e2613976197972a, []int{0}
}
func (m *MaintenanceReservation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MaintenanceReservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MaintenanceReservation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MaintenanceReservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintenanceReservation.Merge(m, src)
}
func (m *MaintenanceReservation) XXX_Size() int {
	return m.Size()
}
func (m *MaintenanceReservation) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintenanceReservation.DiscardUnknown(m)
}

var xxx_messageInfo_MaintenanceReservation proto.InternalMessageInfo

func (m *MaintenanceReservation) GetReservationId() uint64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *MaintenanceReservation) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *MaintenanceReservation) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *MaintenanceReservation) GetDurationBlocks() uint64 {
	if m != nil {
		return m.DurationBlocks
	}
	return 0
}

func (m *MaintenanceReservation) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *MaintenanceReservation) GetStatus() MaintenanceReservationStatus {
	if m != nil {
		return m.Status
	}
	return MaintenanceReservationStatus_MAINTENANCE_RESERVATION_STATUS_UNSPECIFIED
}

func (m *MaintenanceReservation) GetActivationWarning() string {
	if m != nil {
		return m.ActivationWarning
	}
	return ""
}

// MaintenanceState holds per-participant maintenance metadata, keyed by participant address.
type MaintenanceState struct {
	Participant  string `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	CreditBlocks uint64 `protobuf:"varint,2,opt,name=credit_blocks,json=creditBlocks,proto3" json:"credit_blocks,omitempty"`
	// Earliest epoch covered by the most recent maintenance window (set on
	// activation). Combined with last_maintenance_end_epoch, defines the
	// [start, end] range of epochs in which credit accrual is suppressed
	// for the participant's most recent window.
	LastMaintenanceEpoch   uint64 `protobuf:"varint,3,opt,name=last_maintenance_epoch,json=lastMaintenanceEpoch,proto3" json:"last_maintenance_epoch,omitempty"`
	ActiveReservationId    uint64 `protobuf:"varint,4,opt,name=active_reservation_id,json=activeReservationId,proto3" json:"active_reservation_id,omitempty"`
	ScheduledReservationId uint64 `protobuf:"varint,5,opt,name=scheduled_reservation_id,json=scheduledReservationId,proto3" json:"scheduled_reservation_id,omitempty"`
	// Latest epoch covered by the most recent maintenance window. Set on
	// completion (BeginBlock) to the epoch in which the window's last block
	// fell. While the window is still active, this stays at the activation
	// epoch and the active_reservation_id check covers the in-progress epochs.
	LastMaintenanceEndEpoch uint64 `protobuf:"varint,6,opt,name=last_maintenance_end_epoch,json=lastMaintenanceEndEpoch,proto3" json:"last_maintenance_end_epoch,omitempty"`
}

func (m *MaintenanceState) Reset()         { *m = MaintenanceState{} }
func (m *MaintenanceState) String() string { return proto.CompactTextString(m) }
func (*MaintenanceState) ProtoMessage()    {}
func (*MaintenanceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e2613976197972a, []int{1}
}
func (m *MaintenanceState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MaintenanceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MaintenanceState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MaintenanceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintenanceState.Merge(m, src)
}
func (m *MaintenanceState) XXX_Size() int {
	return m.Size()
}
func (m *MaintenanceState) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintenanceState.DiscardUnknown(m)
}

var xxx_messageInfo_MaintenanceState proto.InternalMessageInfo

func (m *MaintenanceState) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *MaintenanceState) GetCreditBlocks() uint64 {
	if m != nil {
		return m.CreditBlocks
	}
	return 0
}

func (m *MaintenanceState) GetLastMaintenanceEpoch() uint64 {
	if m != nil {
		return m.LastMaintenanceEpoch
	}
	return 0
}

func (m *MaintenanceState) GetActiveReservationId() uint64 {
	if m != nil {
		return m.ActiveReservationId
	}
	return 0
}

func (m *MaintenanceState) GetScheduledReservationId() uint64 {
	if m != nil {
		return m.ScheduledReservationId
	}
	return 0
}

func (m *MaintenanceState) GetLastMaintenanceEndEpoch() uint64 {
	if m != nil {
		return m.LastMaintenanceEndEpoch
	}
	return 0
}

// MaintenanceTransition is an entry in the exact-height transition schedule for BeginBlock processing.
type MaintenanceTransition struct {
	BlockHeight   int64                     `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	ReservationId uint64                    `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Type          MaintenanceTransitionType `protobuf:"varint,3,opt,name=type,proto3,enum=inference.inference.MaintenanceTransitionType" json:"type,omitempty"`
}

func (m *MaintenanceTransition) Reset()         { *m = MaintenanceTransition{} }
func (m *MaintenanceTransition) String() string { return proto.CompactTextString(m) }
func (*MaintenanceTransition) ProtoMessage()    {}
func (*MaintenanceTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e2613976197972a, []int{2}
}
func (m *MaintenanceTransition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MaintenanceTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MaintenanceTransition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MaintenanceTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintenanceTransition.Merge(m, src)
}
func (m *MaintenanceTransition) XXX_Size() int {
	return m.Size()
}
func (m *MaintenanceTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintenanceTransition.DiscardUnknown(m)
}

var xxx_messageInfo_MaintenanceTransition proto.InternalMessageInfo

func (m *MaintenanceTransition) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MaintenanceTransition) GetReservationId() uint64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *MaintenanceTransition) GetType() MaintenanceTransitionType {
	if m != nil {
		return m.Type
	}
	return MaintenanceTransitionType_MAINTENANCE_TRANSITION_TYPE_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("inference.inference.MaintenanceReservationStatus", MaintenanceReservationStatus_name, MaintenanceReservationStatus_value)
	proto.RegisterEnum("inference.inference.MaintenanceTransitionType", MaintenanceTransitionType_name, MaintenanceTransitionType_value)
	proto.RegisterType((*MaintenanceReservation)(nil), "inference.inference.MaintenanceReservation")
	proto.RegisterType((*MaintenanceState)(nil), "inference.inference.MaintenanceState")
	proto.RegisterType((*MaintenanceTransition)(nil), "inference.inference.MaintenanceTransition")
}

func init() {
	proto.RegisterFile("inference/inference/maintenance.proto", fileDescriptor_3e2613976197972a)
}

var fileDescriptor_3e2613976197972a = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdf, 0x4e, 0xd3, 0x50,
	0x18, 0xdf, 0x29, 0x63, 0x86, 0x0f, 0x98, 0xf5, 0x20, 0x58, 0x8d, 0x2e, 0x03, 0x25, 0x4c, 0xd4,
	0x12, 0x51, 0x13, 0x13, 0xaf, 0xba, 0xed, 0x18, 0x9a, 0xc0, 0x20, 0x6d, 0xc1, 0xe8, 0x4d, 0xd3,
	0xb5, 0x47, 0x76, 0x22, 0xb4, 0xcd, 0xe9, 0x99, 0xba, 0x5b, 0x9f, 0xc0, 0x07, 0xf0, 0xd6, 0x97,
	0xf0, 0x01, 0x8c, 0x97, 0x5c, 0x7a, 0x69, 0xe0, 0x45, 0xcc, 0xce, 0x3a, 0x56, 0xca, 0x64, 0xde,
	0x9d, 0xfe, 0x7e, 0xdf, 0xbf, 0xdf, 0xf7, 0xfd, 0x52, 0x58, 0x65, 0xe1, 0x7b, 0xca, 0x69, 0xe8,
	0xd3, 0x8d, 0xd1, 0xeb, 0xd8, 0x63, 0xa1, 0xa0, 0xa1, 0x17, 0xfa, 0x54, 0x8f, 0x79, 0x24, 0x22,
	0xbc, 0x70, 0x4e, 0xea, 0xe7, 0xaf, 0x95, 0x9f, 0x0a, 0x2c, 0xed, 0x8c, 0x42, 0x2d, 0x9a, 0x50,
	0xfe, 0xd1, 0x13, 0x2c, 0x0a, 0xf1, 0x2a, 0x94, 0xf9, 0xe8, 0xd3, 0x65, 0x81, 0x86, 0xaa, 0xa8,
	0x56, 0xb4, 0xe6, 0x33, 0xa8, 0x19, 0xe0, 0x2a, 0xcc, 0xc6, 0x1e, 0x17, 0xcc, 0x67, 0xb1, 0x17,
	0x0a, 0x4d, 0xa9, 0xa2, 0xda, 0x8c, 0x95, 0x85, 0xf0, 0x32, 0xcc, 0x25, 0xc2, 0xe3, 0xc2, 0xed,
	0x50, 0x76, 0xd8, 0x11, 0xda, 0x54, 0x15, 0xd5, 0xa6, 0xac, 0x59, 0x89, 0x6d, 0x49, 0x08, 0xaf,
	0xc1, 0xf5, 0xa0, 0xcb, 0x07, 0x8d, 0xda, 0x47, 0x91, 0xff, 0x21, 0xd1, 0x8a, 0xb2, 0x59, 0x79,
	0x08, 0xd7, 0x25, 0x8a, 0xef, 0x01, 0xf8, 0x9c, 0x7a, 0x82, 0x06, 0x6e, 0xbb, 0xa7, 0x4d, 0xcb,
	0x66, 0x33, 0x29, 0x52, 0xef, 0x61, 0x13, 0x4a, 0x89, 0xf0, 0x44, 0x37, 0xd1, 0x4a, 0x55, 0x54,
	0x2b, 0x6f, 0x3e, 0xd5, 0xc7, 0x88, 0xd6, 0xc7, 0x0b, 0xb6, 0x65, 0xa2, 0x95, 0x16, 0xc0, 0x4f,
	0x00, 0x7b, 0xbe, 0x60, 0xa9, 0xfa, 0x4f, 0x1e, 0x0f, 0x59, 0x78, 0xa8, 0x5d, 0x93, 0x1d, 0x6f,
	0x8c, 0x98, 0x37, 0x03, 0x62, 0xe5, 0x87, 0x02, 0x6a, 0xa6, 0x6e, 0xbf, 0x18, 0xcd, 0xef, 0x06,
	0x5d, 0xde, 0xcd, 0x7d, 0x98, 0xf7, 0x39, 0x0d, 0x98, 0x18, 0xca, 0x56, 0xa4, 0xec, 0xb9, 0x01,
	0x98, 0x8a, 0x7e, 0x0e, 0x4b, 0x47, 0x5e, 0x22, 0xdc, 0xcc, 0x4d, 0x5d, 0x1a, 0x47, 0x7e, 0x47,
	0xae, 0xb2, 0x68, 0xdd, 0xec, 0xb3, 0x99, 0xe6, 0xa4, 0xcf, 0xe1, 0x4d, 0x58, 0x94, 0x63, 0x52,
	0x37, 0x77, 0xc6, 0xc1, 0x66, 0x17, 0x06, 0xa4, 0x75, 0xe1, 0x98, 0x2f, 0x41, 0x4b, 0xfc, 0x0e,
	0x0d, 0xba, 0x47, 0x34, 0xc8, 0xa7, 0x4d, 0xcb, 0xb4, 0xa5, 0x73, 0xfe, 0x62, 0xe6, 0x2b, 0xb8,
	0x73, 0x79, 0xc6, 0x30, 0x48, 0xe7, 0x2c, 0xc9, 0xdc, 0x5b, 0xf9, 0x39, 0xc3, 0x40, 0x8e, 0xba,
	0xf2, 0x1d, 0xc1, 0x62, 0x06, 0x77, 0xb8, 0x17, 0x26, 0x4c, 0x9a, 0x70, 0x19, 0xe6, 0xe4, 0x62,
	0x86, 0xde, 0x41, 0x03, 0xef, 0x48, 0x2c, 0xf5, 0xce, 0x65, 0x9f, 0x2a, 0xe3, 0x7c, 0x5a, 0x87,
	0xa2, 0xe8, 0xc5, 0x54, 0xae, 0xac, 0xbc, 0xa9, 0x4f, 0x32, 0xc6, 0x68, 0x06, 0xa7, 0x17, 0x53,
	0x4b, 0xe6, 0xae, 0x7f, 0x51, 0xe0, 0xee, 0x55, 0xe6, 0xc1, 0x3a, 0xac, 0xef, 0x18, 0x66, 0xcb,
	0x21, 0x2d, 0xa3, 0xd5, 0x20, 0xae, 0x45, 0x6c, 0x62, 0x1d, 0x18, 0x8e, 0xb9, 0xdb, 0x72, 0x6d,
	0xc7, 0x70, 0xf6, 0x6d, 0x77, 0xbf, 0x65, 0xef, 0x91, 0x86, 0xf9, 0xda, 0x24, 0x4d, 0xb5, 0x80,
	0x1f, 0x43, 0x6d, 0x42, 0xbc, 0xdd, 0xd8, 0x22, 0xcd, 0xfd, 0x6d, 0xd2, 0x54, 0x11, 0x7e, 0x08,
	0xab, 0x13, 0xa2, 0x8d, 0x86, 0x63, 0x1e, 0x10, 0x55, 0xf9, 0x8f, 0xc2, 0x8d, 0xdd, 0x9d, 0xbd,
	0x6d, 0xe2, 0x90, 0xa6, 0x3a, 0x85, 0x1f, 0xc1, 0xda, 0xa4, 0xe8, 0x3e, 0xd1, 0x9f, 0xa2, 0xb8,
	0xfe, 0x0d, 0xc1, 0xed, 0x7f, 0x2e, 0x2a, 0x5f, 0xca, 0xb1, 0x8c, 0x96, 0x6d, 0xca, 0x4a, 0xce,
	0xdb, 0x3d, 0x92, 0x93, 0x5f, 0x83, 0x07, 0x57, 0x05, 0x4b, 0x35, 0x86, 0x43, 0x54, 0x34, 0x29,
	0x72, 0x28, 0x46, 0x55, 0xea, 0xbb, 0xbf, 0x4e, 0x2b, 0xe8, 0xe4, 0xb4, 0x82, 0xfe, 0x9c, 0x56,
	0xd0, 0xd7, 0xb3, 0x4a, 0xe1, 0xe4, 0xac, 0x52, 0xf8, 0x7d, 0x56, 0x29, 0xbc, 0x7b, 0x71, 0xc8,
	0x44, 0xa7, 0xdb, 0xd6, 0xfd, 0xe8, 0x78, 0x23, 0xe6, 0x51, 0xd0, 0xf5, 0x45, 0xe2, 0xb3, 0xdc,
	0x7f, 0xf3, 0x73, 0xe6, 0xdd, 0xbf, 0x79, 0xd2, 0x2e, 0xc9, 0xdf, 0xe7, 0xb3, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x21, 0x0d, 0x73, 0x8c, 0x67, 0x05, 0x00, 0x00,
}

func (m *MaintenanceReservation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MaintenanceReservation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MaintenanceReservation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActivationWarning) > 0 {
		i -= len(m.ActivationWarning)
		copy(dAtA[i:], m.ActivationWarning)
		i = encodeVarintMaintenance(dAtA, i, uint64(len(m.ActivationWarning)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Status != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintMaintenance(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x2a
	}
	if m.DurationBlocks != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.DurationBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.StartHeight != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintMaintenance(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0x12
	}
	if m.ReservationId != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.ReservationId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MaintenanceState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MaintenanceState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MaintenanceState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastMaintenanceEndEpoch != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.LastMaintenanceEndEpoch))
		i--
		dAtA[i] = 0x30
	}
	if m.ScheduledReservationId != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.ScheduledReservationId))
		i--
		dAtA[i] = 0x28
	}
	if m.ActiveReservationId != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.ActiveReservationId))
		i--
		dAtA[i] = 0x20
	}
	if m.LastMaintenanceEpoch != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.LastMaintenanceEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.CreditBlocks != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.CreditBlocks))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintMaintenance(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MaintenanceTransition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MaintenanceTransition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MaintenanceTransition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.ReservationId != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.ReservationId))
		i--
		dAtA[i] = 0x10
	}
	if m.BlockHeight != 0 {
		i = encodeVarintMaintenance(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMaintenance(dAtA []byte, offset int, v uint64) int {
	offset -= sovMaintenance(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MaintenanceReservation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReservationId != 0 {
		n += 1 + sovMaintenance(uint64(m.ReservationId))
	}
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovMaintenance(uint64(l))
	}
	if m.StartHeight != 0 {
		n += 1 + sovMaintenance(uint64(m.StartHeight))
	}
	if m.DurationBlocks != 0 {
		n += 1 + sovMaintenance(uint64(m.DurationBlocks))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovMaintenance(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovMaintenance(uint64(m.Status))
	}
	l = len(m.ActivationWarning)
	if l > 0 {
		n += 1 + l + sovMaintenance(uint64(l))
	}
	return n
}

func (m *MaintenanceState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovMaintenance(uint64(l))
	}
	if m.CreditBlocks != 0 {
		n += 1 + sovMaintenance(uint64(m.CreditBlocks))
	}
	if m.LastMaintenanceEpoch != 0 {
		n += 1 + sovMaintenance(uint64(m.LastMaintenanceEpoch))
	}
	if m.ActiveReservationId != 0 {
		n += 1 + sovMaintenance(uint64(m.ActiveReservationId))
	}
	if m.ScheduledReservationId != 0 {
		n += 1 + sovMaintenance(uint64(m.ScheduledReservationId))
	}
	if m.LastMaintenanceEndEpoch != 0 {
		n += 1 + sovMaintenance(uint64(m.LastMaintenanceEndEpoch))
	}
	return n
}

func (m *MaintenanceTransition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovMaintenance(uint64(m.BlockHeight))
	}
	if m.ReservationId != 0 {
		n += 1 + sovMaintenance(uint64(m.ReservationId))
	}
	if m.Type != 0 {
		n += 1 + sovMaintenance(uint64(m.Type))
	}
	return n
}

func sovMaintenance(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMaintenance(x uint64) (n int) {
	return sovMaintenance(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MaintenanceReservation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaintenance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MaintenanceReservation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MaintenanceReservation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservationId", wireType)
			}
			m.ReservationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReservationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaintenance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaintenance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationBlocks", wireType)
			}
			m.DurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DurationBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaintenance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaintenance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= MaintenanceReservationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationWarning", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaintenance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaintenance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivationWarning = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaintenance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaintenance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MaintenanceState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaintenance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MaintenanceState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MaintenanceState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaintenance
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaintenance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreditBlocks", wireType)
			}
			m.CreditBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreditBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMaintenanceEpoch", wireType)
			}
			m.LastMaintenanceEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastMaintenanceEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveReservationId", wireType)
			}
			m.ActiveReservationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveReservationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledReservationId", wireType)
			}
			m.ScheduledReservationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScheduledReservationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMaintenanceEndEpoch", wireType)
			}
			m.LastMaintenanceEndEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastMaintenanceEndEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMaintenance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaintenance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MaintenanceTransition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaintenance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MaintenanceTransition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MaintenanceTransition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservationId", wireType)
			}
			m.ReservationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReservationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= MaintenanceTransitionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMaintenance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaintenance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMaintenance(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMaintenance
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaintenance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMaintenance
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMaintenance
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMaintenance
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMaintenance        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMaintenance          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMaintenance = fmt.Errorf("proto: unexpected end of group")
)
